/**
 * Ice biome craft recipes unlocked by exploring world props (E once).
 * Generated by scripts/generate-ice-biome-catalog.mjs
 */
export interface IceBiomeRecipe {
  id: string;
  name: string;
  resultItemId: string | null | undefined;
  resultAssetId: string;
  nodeName: string;
  profession: string;
  tier: number;
  inputs: Array<{ itemId: string; quantity: number }>;
  learnOnce: true;
  learnSources: string[];
  biomes: string[];
  description: string;
}

export const ICE_BIOME_RECIPES: IceBiomeRecipe[] = [
  {
    "id": "recipe_ice_bridge",
    "name": "Recipe: Bridge",
    "resultItemId": "item_ice_bridge",
    "resultAssetId": "ice_bridge",
    "nodeName": "Bridge",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 20
      },
      {
        "itemId": "rope",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Bridge and pressing E (once per character). Crossing bridge for ravines / ice paths"
  },
  {
    "id": "recipe_ice_swing",
    "name": "Recipe: Swing",
    "resultItemId": "item_ice_swing",
    "resultAssetId": "ice_swing",
    "nodeName": "Swing",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Swing and pressing E (once per character). Event island decor / lore prop — E learns craft recipe"
  },
  {
    "id": "recipe_ice_bridge_sleepering",
    "name": "Recipe: Bridge Sleeper",
    "resultItemId": "item_ice_bridge_sleepering",
    "resultAssetId": "ice_bridge_sleepering",
    "nodeName": "Bridge_sleepering",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 20
      },
      {
        "itemId": "rope",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Bridge Sleeper and pressing E (once per character). Crossing bridge for ravines / ice paths"
  },
  {
    "id": "recipe_ice_sleepering_bag_1",
    "name": "Recipe: Sleeper Bag 1",
    "resultItemId": "item_ice_sleepering_bag_1",
    "resultAssetId": "ice_sleepering_bag_1",
    "nodeName": "Sleepering_Bag_1",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 16
      },
      {
        "itemId": "stone",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Bag 1 and pressing E (once per character). Sleeper craft station (extractor / dryer / crusher / bag bench) — NPC base teach via E"
  },
  {
    "id": "recipe_ice_sleepering_extractor",
    "name": "Recipe: Sleeper Extractor",
    "resultItemId": "item_ice_sleepering_extractor",
    "resultAssetId": "ice_sleepering_extractor",
    "nodeName": "Sleepering_extractor",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 16
      },
      {
        "itemId": "stone",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Extractor and pressing E (once per character). Sleeper craft station (extractor / dryer / crusher / bag bench) — NPC base teach via E"
  },
  {
    "id": "recipe_ice_sleepering_seed_dryer",
    "name": "Recipe: Sleeper Seed Dryer",
    "resultItemId": "item_ice_sleepering_seed_dryer",
    "resultAssetId": "ice_sleepering_seed_dryer",
    "nodeName": "Sleepering_seed_dryer",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 16
      },
      {
        "itemId": "stone",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Seed Dryer and pressing E (once per character). Sleeper craft station (extractor / dryer / crusher / bag bench) — NPC base teach via E"
  },
  {
    "id": "recipe_ice_sleepering_crusher",
    "name": "Recipe: Sleeper Crusher",
    "resultItemId": "item_ice_sleepering_crusher",
    "resultAssetId": "ice_sleepering_crusher",
    "nodeName": "Sleepering_crusher",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 16
      },
      {
        "itemId": "stone",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Crusher and pressing E (once per character). Sleeper craft station (extractor / dryer / crusher / bag bench) — NPC base teach via E"
  },
  {
    "id": "recipe_ice_sleepering_bag_2",
    "name": "Recipe: Sleeper Bag 2",
    "resultItemId": "item_ice_sleepering_bag_2",
    "resultAssetId": "ice_sleepering_bag_2",
    "nodeName": "Sleepering_bag_2",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      },
      {
        "itemId": "iron",
        "quantity": 1
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Bag 2 and pressing E (once per character). Barrel storage for camps / deserted islands"
  },
  {
    "id": "recipe_ice_sleppering_powder_bag_2",
    "name": "Recipe: Sleeper Powder Bag 2",
    "resultItemId": "item_ice_sleppering_powder_bag_2",
    "resultAssetId": "ice_sleppering_powder_bag_2",
    "nodeName": "Sleppering_powder_bag_2",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "cloth",
        "quantity": 4
      },
      {
        "itemId": "herbs",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Powder Bag 2 and pressing E (once per character). Dream powder bag/crate — mystic reagent storage; E learns recipe"
  },
  {
    "id": "recipe_ice_sleppering_powder_bag_3",
    "name": "Recipe: Sleeper Powder Bag 3",
    "resultItemId": "item_ice_sleppering_powder_bag_3",
    "resultAssetId": "ice_sleppering_powder_bag_3",
    "nodeName": "Sleppering_powder_bag_3",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "cloth",
        "quantity": 4
      },
      {
        "itemId": "herbs",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Powder Bag 3 and pressing E (once per character). Dream powder bag/crate — mystic reagent storage; E learns recipe"
  },
  {
    "id": "recipe_ice_sleppering_powder_bag_1",
    "name": "Recipe: Sleeper Powder Bag 1",
    "resultItemId": "item_ice_sleppering_powder_bag_1",
    "resultAssetId": "ice_sleppering_powder_bag_1",
    "nodeName": "Sleppering_powder_bag_1",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "cloth",
        "quantity": 4
      },
      {
        "itemId": "herbs",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Powder Bag 1 and pressing E (once per character). Dream powder bag/crate — mystic reagent storage; E learns recipe"
  },
  {
    "id": "recipe_ice_harp",
    "name": "Recipe: Harp",
    "resultItemId": "item_ice_harp",
    "resultAssetId": "ice_harp",
    "nodeName": "Harp",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Harp and pressing E (once per character). Event island decor / lore prop — E learns craft recipe"
  },
  {
    "id": "recipe_ice_sandman_house",
    "name": "Recipe: Sandman House",
    "resultItemId": "item_ice_sandman_house",
    "resultAssetId": "ice_sandman_house",
    "nodeName": "Sandman_house",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 24
      },
      {
        "itemId": "stone",
        "quantity": 12
      },
      {
        "itemId": "cloth",
        "quantity": 6
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sandman House and pressing E (once per character). Snow faction / event settlement building"
  },
  {
    "id": "recipe_ice_box",
    "name": "Recipe: Box",
    "resultItemId": "item_ice_box",
    "resultAssetId": "ice_box",
    "nodeName": "Box",
    "profession": "camp",
    "tier": 0,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "chest",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Box and pressing E (once per character). Supply crate — loot + E to learn crate recipe"
  },
  {
    "id": "recipe_ice_bridge_trunk",
    "name": "Recipe: Bridge Trunk",
    "resultItemId": "item_ice_bridge_trunk",
    "resultAssetId": "ice_bridge_trunk",
    "nodeName": "Bridge_trunk",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 20
      },
      {
        "itemId": "rope",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Bridge Trunk and pressing E (once per character). Crossing bridge for ravines / ice paths"
  },
  {
    "id": "recipe_ice_bridge_trunk_snow",
    "name": "Recipe: Bridge Trunk Snow",
    "resultItemId": "item_ice_bridge_trunk_snow",
    "resultAssetId": "ice_bridge_trunk_snow",
    "nodeName": "Bridge_trunk_snow",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 20
      },
      {
        "itemId": "rope",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Bridge Trunk Snow and pressing E (once per character). Crossing bridge for ravines / ice paths"
  },
  {
    "id": "recipe_ice_barrel_2",
    "name": "Recipe: Barrel 2",
    "resultItemId": "item_ice_barrel_2",
    "resultAssetId": "ice_barrel_2",
    "nodeName": "Barrel_2",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      },
      {
        "itemId": "iron",
        "quantity": 1
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Barrel 2 and pressing E (once per character). Barrel storage for camps / deserted islands"
  },
  {
    "id": "recipe_ice_pannel_1",
    "name": "Recipe: Panel 1",
    "resultItemId": "item_ice_pannel_1",
    "resultAssetId": "ice_pannel_1",
    "nodeName": "Pannel_1",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 1 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_2",
    "name": "Recipe: Panel 2",
    "resultItemId": "item_ice_pannel_2",
    "resultAssetId": "ice_pannel_2",
    "nodeName": "Pannel_2",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 2 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_3",
    "name": "Recipe: Panel 3",
    "resultItemId": "item_ice_pannel_3",
    "resultAssetId": "ice_pannel_3",
    "nodeName": "Pannel_3",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 3 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_4",
    "name": "Recipe: Panel 4",
    "resultItemId": "item_ice_pannel_4",
    "resultAssetId": "ice_pannel_4",
    "nodeName": "Pannel_4",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 4 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_5",
    "name": "Recipe: Panel 5",
    "resultItemId": "item_ice_pannel_5",
    "resultAssetId": "ice_pannel_5",
    "nodeName": "Pannel_5",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 5 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_6",
    "name": "Recipe: Panel 6",
    "resultItemId": "item_ice_pannel_6",
    "resultAssetId": "ice_pannel_6",
    "nodeName": "Pannel_6",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 6 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_7",
    "name": "Recipe: Panel 7",
    "resultItemId": "item_ice_pannel_7",
    "resultAssetId": "ice_pannel_7",
    "nodeName": "Pannel_7",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 7 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_8",
    "name": "Recipe: Panel 8",
    "resultItemId": "item_ice_pannel_8",
    "resultAssetId": "ice_pannel_8",
    "nodeName": "Pannel_8",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 8 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_9",
    "name": "Recipe: Panel 9",
    "resultItemId": "item_ice_pannel_9",
    "resultAssetId": "ice_pannel_9",
    "nodeName": "Pannel_9",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 9 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_10",
    "name": "Recipe: Panel 10",
    "resultItemId": "item_ice_pannel_10",
    "resultAssetId": "ice_pannel_10",
    "nodeName": "Pannel_10",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 10 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_11",
    "name": "Recipe: Panel 11",
    "resultItemId": "item_ice_pannel_11",
    "resultAssetId": "ice_pannel_11",
    "nodeName": "Pannel_11",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 11 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_12",
    "name": "Recipe: Panel 12",
    "resultItemId": "item_ice_pannel_12",
    "resultAssetId": "ice_pannel_12",
    "nodeName": "Pannel_12",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 12 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_sled",
    "name": "Recipe: Sled",
    "resultItemId": "item_ice_sled",
    "resultAssetId": "ice_sled",
    "nodeName": "Sled",
    "profession": "engineering",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 12
      },
      {
        "itemId": "fiber",
        "quantity": 6
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sled and pressing E (once per character). Over-snow sled transport"
  },
  {
    "id": "recipe_ice_sandman_bed",
    "name": "Recipe: Sandman Bed",
    "resultItemId": "item_ice_sandman_bed",
    "resultAssetId": "ice_sandman_bed",
    "nodeName": "Sandman_Bed",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 24
      },
      {
        "itemId": "stone",
        "quantity": 12
      },
      {
        "itemId": "cloth",
        "quantity": 6
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sandman Bed and pressing E (once per character). Snow faction / event settlement building"
  },
  {
    "id": "recipe_ice_boat",
    "name": "Recipe: Boat",
    "resultItemId": "item_ice_boat",
    "resultAssetId": "ice_boat",
    "nodeName": "Boat",
    "profession": "engineering",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 30
      },
      {
        "itemId": "cloth",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Boat and pressing E (once per character). Water travel boat for snow shore / ice edge landings"
  },
  {
    "id": "recipe_ice_chest",
    "name": "Recipe: Chest",
    "resultItemId": "item_ice_chest",
    "resultAssetId": "ice_chest",
    "nodeName": "Chest",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "chest",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Chest and pressing E (once per character). World chest — open for loot; E once learns storage chest recipe"
  },
  {
    "id": "recipe_ice_tomb",
    "name": "Recipe: Tomb",
    "resultItemId": "item_ice_tomb",
    "resultAssetId": "ice_tomb",
    "nodeName": "Tomb",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Tomb and pressing E (once per character). Event island decor / lore prop — E learns craft recipe"
  },
  {
    "id": "recipe_ice_campfire",
    "name": "Recipe: Campfire",
    "resultItemId": "item_ice_campfire",
    "resultAssetId": "ice_campfire",
    "nodeName": "Campfire",
    "profession": "cooking",
    "tier": 0,
    "inputs": [
      {
        "itemId": "stone",
        "quantity": 6
      },
      {
        "itemId": "wood",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "camp",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Campfire and pressing E (once per character). Campfire — cook; E at fire learns campfire recipe if not known"
  },
  {
    "id": "recipe_ice_snowy_barrel",
    "name": "Recipe: Snowy Barrel",
    "resultItemId": "item_ice_snowy_barrel",
    "resultAssetId": "ice_snowy_barrel",
    "nodeName": "Snowy_barrel",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      },
      {
        "itemId": "iron",
        "quantity": 1
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Barrel and pressing E (once per character). Barrel storage for camps / deserted islands"
  },
  {
    "id": "recipe_ice_snowy_box",
    "name": "Recipe: Snowy Box",
    "resultItemId": "item_ice_snowy_box",
    "resultAssetId": "ice_snowy_box",
    "nodeName": "Snowy_box",
    "profession": "camp",
    "tier": 0,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "chest",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Box and pressing E (once per character). Supply crate — loot + E to learn crate recipe"
  },
  {
    "id": "recipe_ice_snowy_barrel_2",
    "name": "Recipe: Snowy Barrel 2",
    "resultItemId": "item_ice_snowy_barrel_2",
    "resultAssetId": "ice_snowy_barrel_2",
    "nodeName": "Snowy_barrel_2",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      },
      {
        "itemId": "iron",
        "quantity": 1
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Barrel 2 and pressing E (once per character). Barrel storage for camps / deserted islands"
  },
  {
    "id": "recipe_ice_barrel_1",
    "name": "Recipe: Barrel 1",
    "resultItemId": "item_ice_barrel_1",
    "resultAssetId": "ice_barrel_1",
    "nodeName": "Barrel_1",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 4
      },
      {
        "itemId": "iron",
        "quantity": 1
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Barrel 1 and pressing E (once per character). Barrel storage for camps / deserted islands"
  },
  {
    "id": "recipe_ice_snowy_well",
    "name": "Recipe: Snowy Well",
    "resultItemId": "item_ice_snowy_well",
    "resultAssetId": "ice_snowy_well",
    "nodeName": "Snowy_well",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 24
      },
      {
        "itemId": "stone",
        "quantity": 12
      },
      {
        "itemId": "cloth",
        "quantity": 6
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Well and pressing E (once per character). Snow faction / event settlement building"
  },
  {
    "id": "recipe_ice_fence_1",
    "name": "Recipe: Fence 1",
    "resultItemId": "item_ice_fence_1",
    "resultAssetId": "ice_fence_1",
    "nodeName": "Fence_1",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Fence 1 and pressing E (once per character). Modular fence for snow camps / NPC bases — learn recipe with E once"
  },
  {
    "id": "recipe_ice_fence_2",
    "name": "Recipe: Fence 2",
    "resultItemId": "item_ice_fence_2",
    "resultAssetId": "ice_fence_2",
    "nodeName": "Fence_2",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Fence 2 and pressing E (once per character). Modular fence for snow camps / NPC bases — learn recipe with E once"
  },
  {
    "id": "recipe_ice_fence_3",
    "name": "Recipe: Fence 3",
    "resultItemId": "item_ice_fence_3",
    "resultAssetId": "ice_fence_3",
    "nodeName": "Fence_3",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Fence 3 and pressing E (once per character). Modular fence for snow camps / NPC bases — learn recipe with E once"
  },
  {
    "id": "recipe_ice_snowy_fence_2",
    "name": "Recipe: Snowy Fence 2",
    "resultItemId": "item_ice_snowy_fence_2",
    "resultAssetId": "ice_snowy_fence_2",
    "nodeName": "Snowy_fence_2",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Fence 2 and pressing E (once per character). Modular fence for snow camps / NPC bases — learn recipe with E once"
  },
  {
    "id": "recipe_ice_snowy_fence_1",
    "name": "Recipe: Snowy Fence 1",
    "resultItemId": "item_ice_snowy_fence_1",
    "resultAssetId": "ice_snowy_fence_1",
    "nodeName": "Snowy_fence_1",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Fence 1 and pressing E (once per character). Modular fence for snow camps / NPC bases — learn recipe with E once"
  },
  {
    "id": "recipe_ice_snowy_fence_3",
    "name": "Recipe: Snowy Fence 3",
    "resultItemId": "item_ice_snowy_fence_3",
    "resultAssetId": "ice_snowy_fence_3",
    "nodeName": "Snowy_fence_3",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Snowy Fence 3 and pressing E (once per character). Modular fence for snow camps / NPC bases — learn recipe with E once"
  },
  {
    "id": "recipe_ice_dream_catcher",
    "name": "Recipe: Dream Catcher",
    "resultItemId": "item_ice_dream_catcher",
    "resultAssetId": "ice_dream_catcher",
    "nodeName": "Dream_catcher",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Dream Catcher and pressing E (once per character). Event island decor / lore prop — E learns craft recipe"
  },
  {
    "id": "recipe_ice_book_table",
    "name": "Recipe: Book Table",
    "resultItemId": "item_ice_book_table",
    "resultAssetId": "ice_book_table",
    "nodeName": "Book_table",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 6
      },
      {
        "itemId": "fiber",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Book Table and pressing E (once per character). Event island decor / lore prop — E learns craft recipe"
  },
  {
    "id": "recipe_ice_bridge_stalactite",
    "name": "Recipe: Bridge Stalactite",
    "resultItemId": "item_ice_bridge_stalactite",
    "resultAssetId": "ice_bridge_stalactite",
    "nodeName": "Bridge_stalactite",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 20
      },
      {
        "itemId": "rope",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Bridge Stalactite and pressing E (once per character). Crossing bridge for ravines / ice paths"
  },
  {
    "id": "recipe_ice_sleppering_powder_crate",
    "name": "Recipe: Sleeper Powder Crate",
    "resultItemId": "item_ice_sleppering_powder_crate",
    "resultAssetId": "ice_sleppering_powder_crate",
    "nodeName": "Sleppering_powder_crate",
    "profession": "mystic",
    "tier": 2,
    "inputs": [
      {
        "itemId": "cloth",
        "quantity": 4
      },
      {
        "itemId": "herbs",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sleeper Powder Crate and pressing E (once per character). Dream powder bag/crate — mystic reagent storage; E learns recipe"
  },
  {
    "id": "recipe_ice_pannel_14",
    "name": "Recipe: Panel 14",
    "resultItemId": "item_ice_pannel_14",
    "resultAssetId": "ice_pannel_14",
    "nodeName": "Pannel_14",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 14 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_15",
    "name": "Recipe: Panel 15",
    "resultItemId": "item_ice_pannel_15",
    "resultAssetId": "ice_pannel_15",
    "nodeName": "Pannel_15",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 15 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_16",
    "name": "Recipe: Panel 16",
    "resultItemId": "item_ice_pannel_16",
    "resultAssetId": "ice_pannel_16",
    "nodeName": "Pannel_16",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 16 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_pannel_17",
    "name": "Recipe: Panel 17",
    "resultItemId": "item_ice_pannel_17",
    "resultAssetId": "ice_pannel_17",
    "nodeName": "Pannel_17",
    "profession": "camp",
    "tier": 1,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 8
      },
      {
        "itemId": "iron",
        "quantity": 2
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Panel 17 and pressing E (once per character). Modular wall/panel piece for snow bases"
  },
  {
    "id": "recipe_ice_sandman_house_light",
    "name": "Recipe: Sandman House Light",
    "resultItemId": "item_ice_sandman_house_light",
    "resultAssetId": "ice_sandman_house_light",
    "nodeName": "Sandman_House_light",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 24
      },
      {
        "itemId": "stone",
        "quantity": 12
      },
      {
        "itemId": "cloth",
        "quantity": 6
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sandman House Light and pressing E (once per character). Snow faction / event settlement building"
  },
  {
    "id": "recipe_ice_sandman_pillow",
    "name": "Recipe: Sandman Pillow",
    "resultItemId": "item_ice_sandman_pillow",
    "resultAssetId": "ice_sandman_pillow",
    "nodeName": "Sandman_pillow",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 24
      },
      {
        "itemId": "stone",
        "quantity": 12
      },
      {
        "itemId": "cloth",
        "quantity": 6
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "npc_base",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Sandman Pillow and pressing E (once per character). Snow faction / event settlement building"
  },
  {
    "id": "recipe_ice_bridge_trunk",
    "name": "Recipe: Bridge Trunk",
    "resultItemId": "item_ice_bridge_trunk",
    "resultAssetId": "ice_bridge_trunk",
    "nodeName": "Bridge_trunk.001",
    "profession": "camp",
    "tier": 2,
    "inputs": [
      {
        "itemId": "wood",
        "quantity": 20
      },
      {
        "itemId": "rope",
        "quantity": 4
      }
    ],
    "learnOnce": true,
    "learnSources": [
      "world_prop",
      "chest",
      "camp",
      "npc_base",
      "event_island"
    ],
    "biomes": [
      "frostbite_expanse",
      "snow",
      "mountain",
      "event_snow",
      "event_mountain"
    ],
    "description": "Learn by standing over Bridge Trunk and pressing E (once per character). Crossing bridge for ravines / ice paths"
  }
];

export function getIceBiomeRecipe(id: string): IceBiomeRecipe | undefined {
  return ICE_BIOME_RECIPES.find((r) => r.id === id);
}

export function getIceBiomeRecipeByAssetId(assetId: string): IceBiomeRecipe | undefined {
  return ICE_BIOME_RECIPES.find((r) => r.resultAssetId === assetId);
}
