/**
 * Ninja throwables + projectiles — one weapon entry per mesh from ninja_equipment.glb
 * Generated by grudge-arena/scripts/process-ninja-equipment.mjs
 */

export type NinjaThrowableId =
  | "shuriken-4"
  | "shuriken-4-circled"
  | "shuriken-6"
  | "shuriken-3"
  | "shuriken-8"
  | "kunai";

export interface NinjaWeaponDef {
  id: string;
  meshId: NinjaThrowableId;
  label: string;
  subtype: "shuriken" | "kunai";
  rarity: string;
  description: string;
  throwableUrl: string;
  projectileUrl: string;
  damage: number;
  speed: number;
  spin: number;
  range: number;
  pierce: number;
  stackMax: number;
  cooldown: number;
  gravity: number;
  stickOnHit: boolean;
  returnable: boolean;
  hasChain: boolean;
}

export const NINJA_WEAPONS: NinjaWeaponDef[] = [
  {
    "id": "weapon:ninja:shuriken-4",
    "meshId": "shuriken-4",
    "label": "Cross Shuriken",
    "subtype": "shuriken",
    "rarity": "common",
    "description": "Classic four-point shuriken. Balanced damage and range.",
    "throwableUrl": "https://assets.grudge-studio.com/models/weapons/throwables/shuriken-4.glb",
    "projectileUrl": "https://assets.grudge-studio.com/models/weapons/projectiles/shuriken-4.glb",
    "damage": 16,
    "speed": 24,
    "spin": 14,
    "range": 20,
    "pierce": 0,
    "stackMax": 15,
    "cooldown": 0.45,
    "gravity": 4,
    "stickOnHit": false,
    "returnable": false,
    "hasChain": false
  },
  {
    "id": "weapon:ninja:shuriken-4-circled",
    "meshId": "shuriken-4-circled",
    "label": "Ring Shuriken",
    "subtype": "shuriken",
    "rarity": "uncommon",
    "description": "Circled four-point star — denser rim, slight pierce.",
    "throwableUrl": "https://assets.grudge-studio.com/models/weapons/throwables/shuriken-4-circled.glb",
    "projectileUrl": "https://assets.grudge-studio.com/models/weapons/projectiles/shuriken-4-circled.glb",
    "damage": 18,
    "speed": 22,
    "spin": 16,
    "range": 22,
    "pierce": 1,
    "stackMax": 12,
    "cooldown": 0.45,
    "gravity": 4,
    "stickOnHit": false,
    "returnable": false,
    "hasChain": false
  },
  {
    "id": "weapon:ninja:shuriken-6",
    "meshId": "shuriken-6",
    "label": "Hex Star Shuriken",
    "subtype": "shuriken",
    "rarity": "uncommon",
    "description": "Six-point star. Heavier cut, longer flight.",
    "throwableUrl": "https://assets.grudge-studio.com/models/weapons/throwables/shuriken-6.glb",
    "projectileUrl": "https://assets.grudge-studio.com/models/weapons/projectiles/shuriken-6.glb",
    "damage": 22,
    "speed": 20,
    "spin": 12,
    "range": 24,
    "pierce": 1,
    "stackMax": 10,
    "cooldown": 0.45,
    "gravity": 4,
    "stickOnHit": false,
    "returnable": false,
    "hasChain": false
  },
  {
    "id": "weapon:ninja:shuriken-3",
    "meshId": "shuriken-3",
    "label": "Tri-Blade Shuriken",
    "subtype": "shuriken",
    "rarity": "common",
    "description": "Light three-point star. Fast spin, short throw.",
    "throwableUrl": "https://assets.grudge-studio.com/models/weapons/throwables/shuriken-3.glb",
    "projectileUrl": "https://assets.grudge-studio.com/models/weapons/projectiles/shuriken-3.glb",
    "damage": 12,
    "speed": 28,
    "spin": 18,
    "range": 18,
    "pierce": 0,
    "stackMax": 20,
    "cooldown": 0.45,
    "gravity": 4,
    "stickOnHit": false,
    "returnable": false,
    "hasChain": false
  },
  {
    "id": "weapon:ninja:shuriken-8",
    "meshId": "shuriken-8",
    "label": "Octa Shuriken",
    "subtype": "shuriken",
    "rarity": "rare",
    "description": "Eight-point war star. Slow throw, high shred.",
    "throwableUrl": "https://assets.grudge-studio.com/models/weapons/throwables/shuriken-8.glb",
    "projectileUrl": "https://assets.grudge-studio.com/models/weapons/projectiles/shuriken-8.glb",
    "damage": 28,
    "speed": 18,
    "spin": 10,
    "range": 26,
    "pierce": 2,
    "stackMax": 8,
    "cooldown": 0.45,
    "gravity": 4,
    "stickOnHit": false,
    "returnable": false,
    "hasChain": false
  },
  {
    "id": "weapon:ninja:kunai",
    "meshId": "kunai",
    "label": "Chained Kunai",
    "subtype": "kunai",
    "rarity": "rare",
    "description": "Weighted kunai with chain. Stick or yank; melee-throw hybrid.",
    "throwableUrl": "https://assets.grudge-studio.com/models/weapons/throwables/kunai.glb",
    "projectileUrl": "https://assets.grudge-studio.com/models/weapons/projectiles/kunai.glb",
    "damage": 32,
    "speed": 16,
    "spin": 2,
    "range": 14,
    "pierce": 0,
    "stackMax": 5,
    "cooldown": 1.2,
    "gravity": 9.5,
    "stickOnHit": true,
    "returnable": true,
    "hasChain": true
  }
] as NinjaWeaponDef[];

export const NINJA_WEAPON_BY_ID: Record<string, NinjaWeaponDef> = Object.fromEntries(
  NINJA_WEAPONS.map((w) => [w.meshId, w]),
);

export const NINJA_THROWABLES = NINJA_WEAPONS.map((w) => ({
  id: `throwable:ninja:${w.meshId}`,
  weaponId: w.meshId,
  meshUrl: w.throwableUrl,
  damage: w.damage,
  cooldown: w.cooldown,
  stackMax: w.stackMax,
}));

export const NINJA_PROJECTILES = NINJA_WEAPONS.map((w) => ({
  id: `projectile:ninja:${w.meshId}`,
  weaponId: w.meshId,
  meshUrl: w.projectileUrl,
  flightSpeed: w.speed,
  spinRate: w.spin,
  gravity: w.gravity,
  stickOnHit: w.stickOnHit,
  returnable: w.returnable,
}));

export function resolveNinjaThrowableMesh(id: string): string {
  const w = NINJA_WEAPON_BY_ID[id.replace(/^throwable:ninja:/, "").replace(/^weapon:ninja:/, "")];
  return w?.throwableUrl ?? NINJA_WEAPONS[0].throwableUrl;
}

export function resolveNinjaProjectileMesh(id: string): string {
  const w = NINJA_WEAPON_BY_ID[id.replace(/^projectile:ninja:/, "").replace(/^weapon:ninja:/, "")];
  return w?.projectileUrl ?? NINJA_WEAPONS[0].projectileUrl;
}
