import type { SkillDefinition } from "./types";

export const SKILLS: Record<string, SkillDefinition> = {
  "skill_slash": {
    id: "skill_slash",
    name: "Slash",
    referenceName: "Slash",
    description: "A basic sword attack.",
    icon: "/icons/misc/Slash_07.png",
    category: "attack",
    weaponType: "sword",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 15,
    damageScaling: { stat: "Strength", ratio: 1.2 },
    manaCost: 0,
    staminaCost: 5,
    cooldown: 0,
    castTime: 0.3,
    animation: "slash",
    visualEffect: "slash",
    levelRequirement: 1
  },
  
  "skill_power_strike": {
    id: "skill_power_strike",
    name: "Power Strike",
    referenceName: "PowerStrike",
    description: "A devastating overhead blow that deals heavy damage.",
    icon: "/icons/weapons/Sword_01.png",
    category: "skill",
    weaponType: "sword",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 35,
    damageScaling: { stat: "Strength", ratio: 1.8 },
    manaCost: 10,
    staminaCost: 15,
    cooldown: 2,
    castTime: 0.8,
    animation: "overhead",
    visualEffect: "slash",
    levelRequirement: 3,
    critBonus: 20
  },
  
  "skill_whirlwind": {
    id: "skill_whirlwind",
    name: "Whirlwind",
    referenceName: "Whirlwind",
    description: "Spin attack that hits all nearby enemies.",
    icon: "/icons/misc/CircleF.png",
    category: "skill",
    weaponType: "sword",
    damageType: "physical",
    targetType: "all_enemies",
    baseDamage: 22,
    damageScaling: { stat: "Strength", ratio: 1.4 },
    manaCost: 15,
    staminaCost: 20,
    cooldown: 3,
    castTime: 0.5,
    animation: "slash",
    visualEffect: "slash",
    levelRequirement: 8
  },
  
  "skill_cleave": {
    id: "skill_cleave",
    name: "Cleave",
    referenceName: "Cleave",
    description: "A powerful axe swing that cleaves through armor.",
    icon: "/icons/weapons/Axe_01.png",
    category: "attack",
    weaponType: "axe",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 20,
    damageScaling: { stat: "Strength", ratio: 1.5 },
    manaCost: 0,
    staminaCost: 8,
    cooldown: 0,
    castTime: 0.4,
    animation: "slash",
    visualEffect: "slash",
    levelRequirement: 1,
    statusEffects: [{
      id: "armor_break",
      name: "Armor Broken",
      duration: 2,
      stackable: false,
      type: "debuff",
      statModifiers: { "Phys Def": -15 }
    }]
  },
  
  "skill_raging_blow": {
    id: "skill_raging_blow",
    name: "Raging Blow",
    referenceName: "RagingBlow",
    description: "An enraged attack fueled by battle fury.",
    icon: "/icons/weapons/Axe_04.png",
    category: "skill",
    weaponType: "axe",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 45,
    damageScaling: { stat: "Strength", ratio: 2.0 },
    manaCost: 0,
    staminaCost: 25,
    cooldown: 3,
    castTime: 0.6,
    animation: "overhead",
    visualEffect: "slash",
    levelRequirement: 6,
    critBonus: 25
  },
  
  "skill_skull_splitter": {
    id: "skill_skull_splitter",
    name: "Skull Splitter",
    referenceName: "SkullSplitter",
    description: "Devastating overhead strike that ignores defense.",
    icon: "/icons/weapons/Axe_12.png",
    category: "skill",
    weaponType: "axe",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 55,
    damageScaling: { stat: "Strength", ratio: 2.2 },
    manaCost: 15,
    staminaCost: 30,
    cooldown: 5,
    castTime: 1.0,
    animation: "overhead",
    visualEffect: "blood",
    levelRequirement: 12
  },
  
  "skill_backstab": {
    id: "skill_backstab",
    name: "Backstab",
    referenceName: "Backstab",
    description: "Strike from the shadows for critical damage.",
    icon: "/icons/weapons/Dagger_01.png",
    category: "attack",
    weaponType: "dagger",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 18,
    damageScaling: { stat: "Dexterity", ratio: 1.6 },
    manaCost: 0,
    staminaCost: 6,
    cooldown: 0,
    castTime: 0.2,
    animation: "thrust",
    visualEffect: "slash",
    levelRequirement: 1,
    critBonus: 40
  },
  
  "skill_envenom": {
    id: "skill_envenom",
    name: "Envenom",
    referenceName: "Envenom",
    description: "Coats your blade with deadly poison.",
    icon: "/icons/weapons/Dagger_02.png",
    category: "skill",
    weaponType: "dagger",
    damageType: "poison",
    targetType: "single_enemy",
    baseDamage: 12,
    damageScaling: { stat: "Dexterity", ratio: 1.2 },
    manaCost: 10,
    staminaCost: 10,
    cooldown: 2,
    castTime: 0.3,
    animation: "thrust",
    visualEffect: "poison",
    levelRequirement: 4,
    statusEffects: [{
      id: "venom",
      name: "Envenomed",
      duration: 5,
      stackable: true,
      type: "debuff",
      dotDamage: 10,
      dotType: "poison"
    }]
  },
  
  "skill_shadow_dance": {
    id: "skill_shadow_dance",
    name: "Shadow Dance",
    referenceName: "ShadowDance",
    description: "Become one with shadows, striking multiple times.",
    icon: "/icons/misc/ChaosCircle.png",
    category: "skill",
    weaponType: "dagger",
    damageType: "shadow",
    targetType: "single_enemy",
    baseDamage: 15,
    damageScaling: { stat: "Dexterity", ratio: 1.0 },
    manaCost: 25,
    staminaCost: 20,
    cooldown: 4,
    castTime: 0.4,
    animation: "slash",
    visualEffect: "shadow",
    levelRequirement: 10,
    comboPosition: 5
  },
  
  "skill_aimed_shot": {
    id: "skill_aimed_shot",
    name: "Aimed Shot",
    referenceName: "AimedShot",
    description: "A carefully aimed arrow that deals bonus damage.",
    icon: "/icons/weapons/Bow_01.png",
    category: "attack",
    weaponType: "bow",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 22,
    damageScaling: { stat: "Dexterity", ratio: 1.5 },
    manaCost: 0,
    staminaCost: 8,
    cooldown: 0,
    castTime: 0.6,
    animation: "projectile",
    visualEffect: "slash",
    levelRequirement: 1,
    critBonus: 15
  },
  
  "skill_multi_shot": {
    id: "skill_multi_shot",
    name: "Multi-Shot",
    referenceName: "MultiShot",
    description: "Fire multiple arrows at all enemies.",
    icon: "/icons/weapons/Bow_02.png",
    category: "skill",
    weaponType: "bow",
    damageType: "physical",
    targetType: "all_enemies",
    baseDamage: 16,
    damageScaling: { stat: "Dexterity", ratio: 1.2 },
    manaCost: 15,
    staminaCost: 15,
    cooldown: 2,
    castTime: 0.5,
    animation: "projectile",
    visualEffect: "slash",
    levelRequirement: 5
  },
  
  "skill_explosive_arrow": {
    id: "skill_explosive_arrow",
    name: "Explosive Arrow",
    referenceName: "ExplosiveArrow",
    description: "An arrow that explodes on impact.",
    icon: "/icons/weapons/Crossbow_01.png",
    category: "skill",
    weaponType: "bow",
    damageType: "fire",
    targetType: "aoe",
    baseDamage: 30,
    damageScaling: { stat: "Dexterity", ratio: 1.4 },
    manaCost: 20,
    staminaCost: 12,
    cooldown: 3,
    castTime: 0.8,
    animation: "projectile",
    visualEffect: "fire",
    levelRequirement: 8
  },
  
  "skill_shield_bash": {
    id: "skill_shield_bash",
    name: "Shield Bash",
    referenceName: "ShieldBash",
    description: "Bash the enemy with your shield, stunning them.",
    icon: "/icons/weapons/Hammer_01.png",
    category: "skill",
    weaponType: "mace",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 18,
    damageScaling: { stat: "Strength", ratio: 1.0 },
    manaCost: 0,
    staminaCost: 12,
    cooldown: 2,
    castTime: 0.4,
    animation: "thrust",
    visualEffect: "stun",
    levelRequirement: 1,
    statusEffects: [{
      id: "stunned",
      name: "Stunned",
      duration: 1,
      stackable: false,
      type: "debuff"
    }]
  },
  
  "skill_holy_strike": {
    id: "skill_holy_strike",
    name: "Holy Strike",
    referenceName: "HolyStrike",
    description: "Infuse your weapon with holy energy.",
    icon: "/icons/weapons/Hammer_02.png",
    category: "skill",
    weaponType: "mace",
    damageType: "holy",
    targetType: "single_enemy",
    baseDamage: 25,
    damageScaling: { stat: "Strength", ratio: 1.2 },
    manaCost: 15,
    staminaCost: 10,
    cooldown: 1,
    castTime: 0.5,
    animation: "overhead",
    visualEffect: "holy",
    levelRequirement: 5,
    bonusVsType: "undead"
  },
  
  "skill_staff_strike": {
    id: "skill_staff_strike",
    name: "Staff Strike",
    referenceName: "StaffStrike",
    description: "A basic melee attack with a staff.",
    icon: "/icons/weapons/staff_10.png",
    category: "attack",
    weaponType: "staff",
    damageType: "arcane",
    targetType: "single_enemy",
    baseDamage: 12,
    damageScaling: { stat: "Intellect", ratio: 1.0 },
    manaCost: 0,
    staminaCost: 4,
    cooldown: 0,
    castTime: 0.3,
    animation: "thrust",
    visualEffect: "arcane",
    levelRequirement: 1
  },
  
  "skill_spear_thrust": {
    id: "skill_spear_thrust",
    name: "Spear Thrust",
    referenceName: "SpearThrust",
    description: "A precise thrust with your spear.",
    icon: "/icons/weapons/Spear_01.png",
    category: "attack",
    weaponType: "spear",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 18,
    damageScaling: { stat: "Dexterity", ratio: 1.3 },
    manaCost: 0,
    staminaCost: 6,
    cooldown: 0,
    castTime: 0.35,
    animation: "thrust",
    visualEffect: "slash",
    levelRequirement: 1
  },
  
  "skill_impale": {
    id: "skill_impale",
    name: "Impale",
    referenceName: "Impale",
    description: "Drive your spear through the enemy, causing bleed.",
    icon: "/icons/weapons/Spear_02.png",
    category: "skill",
    weaponType: "spear",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 32,
    damageScaling: { stat: "Dexterity", ratio: 1.6 },
    manaCost: 10,
    staminaCost: 15,
    cooldown: 2,
    castTime: 0.6,
    animation: "thrust",
    visualEffect: "blood",
    levelRequirement: 6,
    statusEffects: [{
      id: "bleed",
      name: "Bleeding",
      duration: 4,
      stackable: true,
      type: "debuff",
      dotDamage: 8,
      dotType: "bleed"
    }]
  },
  
  "skill_feral_strike": {
    id: "skill_feral_strike",
    name: "Feral Strike",
    referenceName: "FeralStrike",
    description: "Attack with primal fury using claws or fists.",
    icon: "/icons/misc/Lava.png",
    category: "attack",
    weaponType: "fist",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 14,
    damageScaling: { stat: "Agility", ratio: 1.4 },
    manaCost: 0,
    staminaCost: 5,
    cooldown: 0,
    castTime: 0.2,
    animation: "slash",
    visualEffect: "slash",
    levelRequirement: 1
  },
  
  "skill_savage_pounce": {
    id: "skill_savage_pounce",
    name: "Savage Pounce",
    referenceName: "SavagePounce",
    description: "Leap at the enemy with bestial ferocity.",
    icon: "/icons/misc/NatureFlower.png",
    category: "skill",
    weaponType: "fist",
    damageType: "physical",
    targetType: "single_enemy",
    baseDamage: 40,
    damageScaling: { stat: "Agility", ratio: 1.8 },
    manaCost: 15,
    staminaCost: 20,
    cooldown: 3,
    castTime: 0.4,
    animation: "thrust",
    visualEffect: "slash",
    levelRequirement: 8,
    critBonus: 30
  },
  
  "skill_taunt": {
    id: "skill_taunt",
    name: "Taunt",
    referenceName: "Taunt",
    description: "Force all enemies to target you.",
    icon: "/icons/misc/Burns.png",
    category: "skill",
    weaponType: "sword",
    damageType: "physical",
    targetType: "all_enemies",
    baseDamage: 0,
    damageScaling: { stat: "Endurance", ratio: 0 },
    manaCost: 5,
    staminaCost: 10,
    cooldown: 3,
    castTime: 0.3,
    animation: "aura",
    visualEffect: "buff_defense",
    levelRequirement: 2,
    statusEffects: [{
      id: "taunted",
      name: "Taunted",
      duration: 2,
      stackable: false,
      type: "debuff"
    }]
  },
  
  "skill_battle_cry": {
    id: "skill_battle_cry",
    name: "Battle Cry",
    referenceName: "BattleCry",
    description: "Boost attack power for all allies.",
    icon: "/icons/misc/Flag Icon.png",
    category: "skill",
    weaponType: "sword",
    damageType: "physical",
    targetType: "all_allies",
    baseDamage: 0,
    damageScaling: { stat: "Tactics", ratio: 0 },
    manaCost: 15,
    staminaCost: 15,
    cooldown: 5,
    castTime: 0.5,
    animation: "buff",
    visualEffect: "buff_attack",
    levelRequirement: 5,
    statusEffects: [{
      id: "battle_fury",
      name: "Battle Fury",
      duration: 3,
      stackable: false,
      type: "buff",
      statModifiers: { "Phys Dmg": 20, Crit: 10 }
    }]
  }
};

export function getSkill(id: string): SkillDefinition | undefined {
  return SKILLS[id];
}

export function getSkillByReferenceName(referenceName: string): SkillDefinition | undefined {
  return Object.values(SKILLS).find(s => s.referenceName === referenceName);
}

export function getSkillsByWeapon(weaponType: SkillDefinition["weaponType"]): SkillDefinition[] {
  return Object.values(SKILLS).filter(s => s.weaponType === weaponType);
}

export function getSkillsByLevel(maxLevel: number): SkillDefinition[] {
  return Object.values(SKILLS).filter(s => s.levelRequirement <= maxLevel);
}
