export interface WeaponStats {
  damage: { base: number; perTier: number };
  hp: { base: number; perTier: number };
  mana: { base: number; perTier: number };
  crit: { base: number; perTier: number };
  block: { base: number; perTier: number };
  defense: { base: number; perTier: number };
}

export interface WeaponSkill {
  name: string;
  description: string;
}

export interface Weapon {
  id: string;
  name: string;
  lore: string;
  stats: WeaponStats;
  skills: {
    hotkey1: WeaponSkill;
    hotkey2: WeaponSkill[];
    hotkey3: WeaponSkill[];
    hotkey4: WeaponSkill;
    passive: WeaponSkill[];
  };
}

export interface WeaponType {
  id: string;
  name: string;
  icon: string;
  category: 'melee' | 'ranged' | 'magic';
  weapons: Weapon[];
}

export const WEAPON_TYPES: Record<string, WeaponType> = {
  SWORD: {
    id: 'SWORD',
    name: 'Sword',
    icon: '⚔️',
    category: 'melee',
    weapons: [
      {
        id: 'sword_bloodfeud',
        name: 'Bloodfeud Blade',
        lore: 'Forged in endless clan blood feuds',
        stats: { damage: { base: 50, perTier: 12 }, hp: { base: 100, perTier: 25 }, mana: { base: 0, perTier: 0 }, crit: { base: 3, perTier: 0.5 }, block: { base: 5, perTier: 1 }, defense: { base: 20, perTier: 6 } },
        skills: {
          hotkey1: { name: 'Vengeful Slash', description: 'Single-target slash, builds 1 Grudge Mark stack (max 3)' },
          hotkey2: [{ name: 'Blood Rush', description: 'Dash forward 8m with AoE damage' }, { name: 'Iron Grudge', description: '3s damage reduction + reflect' }, { name: 'Clan Charge', description: 'Gap-closer charge + 1s stun' }],
          hotkey3: [{ name: 'Heroic Cleave', description: 'Cone AoE clear' }, { name: 'Parry Counter', description: 'Block + counter damage' }, { name: 'Deep Wound', description: 'Apply bleed stack' }],
          hotkey4: { name: 'Crimson Reprisal', description: 'Large AoE slash, heals per enemy hit' },
          passive: [{ name: 'Bloodlust', description: '5% lifesteal' }, { name: 'Swift Vengeance', description: '+15% atk speed' }, { name: 'Deep Cuts', description: '+20% bleed dmg' }]
        }
      },
      {
        id: 'sword_wraithfang',
        name: 'Wraithfang',
        lore: 'Whispers forgotten grudges in the dark',
        stats: { damage: { base: 55, perTier: 13 }, hp: { base: 80, perTier: 20 }, mana: { base: 20, perTier: 10 }, crit: { base: 5, perTier: 0.8 }, block: { base: 3, perTier: 0.8 }, defense: { base: 15, perTier: 5 } },
        skills: {
          hotkey1: { name: 'Vengeful Slash', description: 'Single-target slash, builds Grudge Mark' },
          hotkey2: [{ name: 'Blood Rush', description: 'Dash forward 8m with AoE damage' }, { name: 'Iron Grudge', description: '3s damage reduction + reflect' }, { name: 'Clan Charge', description: 'Gap-closer charge + 1s stun' }],
          hotkey3: [{ name: 'Shadow Edge', description: 'Dash + stun' }, { name: 'Execute', description: 'Bonus dmg <30% HP' }, { name: 'Bleed Chain', description: 'Spread bleed' }, { name: 'Fatal Strike', description: 'High single burst' }],
          hotkey4: { name: "Night's Judgment", description: 'Teleport behind + bleed DoT' },
          passive: [{ name: 'Life Leech', description: 'Heal on hit' }, { name: 'Aggressive Rush', description: '+atk speed on mark' }, { name: 'Grudge Bleed', description: 'Marks explode' }]
        }
      },
      {
        id: 'sword_oathbreaker',
        name: 'Oathbreaker',
        lore: 'Breaks ancient oaths of peace',
        stats: { damage: { base: 48, perTier: 11 }, hp: { base: 120, perTier: 30 }, mana: { base: 0, perTier: 0 }, crit: { base: 2, perTier: 0.4 }, block: { base: 8, perTier: 1.5 }, defense: { base: 25, perTier: 7 } },
        skills: {
          hotkey1: { name: 'Vengeful Slash', description: 'Single-target slash, builds Grudge Mark' },
          hotkey2: [{ name: 'Lunging Strike', description: 'Ranged thrust' }, { name: 'Shadow Dash', description: 'Mobility dash' }, { name: 'Fearful Swipe', description: 'AoE fear' }],
          hotkey3: [{ name: 'Hamstring', description: 'Slow + dmg' }, { name: "Betrayer's Mark", description: 'Reduce healing' }, { name: 'Oathbreak', description: 'Purge enemy buff' }],
          hotkey4: { name: 'Ancestral Curse', description: 'AoE slow + DoT' },
          passive: [{ name: 'Resilience', description: '+defense in crowds' }, { name: 'Armor Pen', description: 'Ignore 10% def' }, { name: 'Block Mastery', description: '+block chance' }]
        }
      },
      {
        id: 'sword_kinrend',
        name: 'Kinrend',
        lore: 'Rends bonds of blood and kinship',
        stats: { damage: { base: 52, perTier: 12 }, hp: { base: 110, perTier: 28 }, mana: { base: 10, perTier: 8 }, crit: { base: 4, perTier: 0.6 }, block: { base: 4, perTier: 1 }, defense: { base: 18, perTier: 6 } },
        skills: {
          hotkey1: { name: 'Vengeful Slash', description: 'Single-target slash, builds Grudge Mark' },
          hotkey2: [{ name: 'Lunging Strike', description: 'Ranged thrust' }, { name: 'Shadow Dash', description: 'Mobility dash' }, { name: 'Fearful Swipe', description: 'AoE fear' }],
          hotkey3: [{ name: 'Kin Strike', description: 'Single high dmg' }, { name: 'Ancestral Fury', description: 'Knockback AoE' }, { name: 'Family Grudge', description: 'Stack DoT' }, { name: 'Root Bind', description: 'Root on mark' }],
          hotkey4: { name: 'Wrath of Kin', description: 'AoE knockback + dmg' },
          passive: [{ name: 'Bloodlust', description: '5% lifesteal' }, { name: 'Swift Vengeance', description: '+15% atk speed' }, { name: 'Deep Cuts', description: '+20% bleed dmg' }]
        }
      },
      {
        id: 'sword_dusksinger',
        name: 'Dusksinger',
        lore: 'Sings of twilight and ending grudges',
        stats: { damage: { base: 53, perTier: 12 }, hp: { base: 90, perTier: 22 }, mana: { base: 30, perTier: 15 }, crit: { base: 6, perTier: 1 }, block: { base: 4, perTier: 0.9 }, defense: { base: 17, perTier: 5 } },
        skills: {
          hotkey1: { name: 'Vengeful Slash', description: 'Single-target slash, builds Grudge Mark' },
          hotkey2: [{ name: 'Blood Rush', description: 'Dash forward 8m with AoE damage' }, { name: 'Iron Grudge', description: '3s damage reduction + reflect' }, { name: 'Clan Charge', description: 'Gap-closer charge + 1s stun' }],
          hotkey3: [{ name: 'Dusk Blade', description: 'Invis dash' }, { name: 'Twilight Fear', description: 'AoE fear' }, { name: 'Bleed Storm', description: 'Multi bleed' }],
          hotkey4: { name: 'Duskfall', description: 'AoE silence + dmg' },
          passive: [{ name: 'Life Leech', description: 'Heal on hit' }, { name: 'Aggressive Rush', description: '+atk speed on mark' }, { name: 'Grudge Explosion', description: 'Marks explode on death' }]
        }
      },
      {
        id: 'sword_emberclad',
        name: 'Emberclad',
        lore: 'Clad in flames of burning hatred',
        stats: { damage: { base: 54, perTier: 13 }, hp: { base: 95, perTier: 23 }, mana: { base: 25, perTier: 12 }, crit: { base: 4, perTier: 0.7 }, block: { base: 6, perTier: 1.2 }, defense: { base: 22, perTier: 6 } },
        skills: {
          hotkey1: { name: 'Vengeful Slash', description: 'Single-target slash, builds Grudge Mark' },
          hotkey2: [{ name: 'Lunging Strike', description: 'Ranged thrust' }, { name: 'Shadow Dash', description: 'Mobility dash' }, { name: 'Fearful Swipe', description: 'AoE fear' }],
          hotkey3: [{ name: 'Flame Slash', description: 'Apply burn stack' }, { name: 'Ember Charge', description: 'Dash + burn' }, { name: 'Heroic Burn', description: 'AoE DoT' }, { name: 'Ignite Mark', description: 'Explode marks' }],
          hotkey4: { name: 'Ember Wrath', description: 'AoE fire nova' },
          passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Attack Speed', description: '+atk speed' }, { name: 'Life Leech', description: 'Heal on hit' }]
        }
      }
    ]
  },
  AXE: {
    id: 'AXE',
    name: 'Axe',
    icon: '🪓',
    category: 'melee',
    weapons: [
      { id: 'axe_gorehowl', name: 'Gorehowl', lore: 'Howls with the gore of fallen foes', stats: { damage: { base: 60, perTier: 15 }, hp: { base: 120, perTier: 30 }, mana: { base: 0, perTier: 0 }, crit: { base: 2, perTier: 0.4 }, block: { base: 4, perTier: 1 }, defense: { base: 25, perTier: 8 } }, skills: { hotkey1: { name: 'Rending Chop', description: 'Single target, applies Bleed stack' }, hotkey2: [{ name: 'Adrenaline Surge', description: '+atk speed buff' }, { name: 'Whirl of Pain', description: 'Channeled AoE' }, { name: 'Bloodletting', description: 'AoE bleed apply' }], hotkey3: [{ name: 'Carnage Spin', description: '360 AoE refresh bleed' }, { name: 'Headcracker', description: 'Single stun' }, { name: 'Veinreaver', description: 'AoE lifesteal' }], hotkey4: { name: 'Apocalypse Cleave', description: 'Large knockback AoE' }, passive: [{ name: 'Life Leech', description: 'Heal on hit' }, { name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Vicious Wounds', description: 'Slow on bleed' }] } },
      { id: 'axe_skullsplitter', name: 'Skullsplitter', lore: 'Splits skulls of grudge bearers', stats: { damage: { base: 62, perTier: 16 }, hp: { base: 110, perTier: 28 }, mana: { base: 10, perTier: 5 }, crit: { base: 3, perTier: 0.5 }, block: { base: 5, perTier: 1.2 }, defense: { base: 23, perTier: 7 } }, skills: { hotkey1: { name: 'Rending Chop', description: 'Single target, applies Bleed stack' }, hotkey2: [{ name: 'Adrenaline Surge', description: '+atk speed buff' }, { name: 'Whirl of Pain', description: 'Channeled AoE' }, { name: 'Bloodletting', description: 'AoE bleed apply' }], hotkey3: [{ name: 'Headcracker', description: 'Stun + dmg' }, { name: 'Ground Rend', description: 'AoE slow' }, { name: 'Ironmaw', description: 'Armor reduce' }], hotkey4: { name: 'Blood Harvest', description: 'AoE heal on hit' }, passive: [{ name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Heavy Hitter', description: '+dmg' }, { name: 'Resilience', description: '+defense' }] } },
      { id: 'axe_veinreaver', name: 'Veinreaver', lore: 'Reaves veins for blood tribute', stats: { damage: { base: 58, perTier: 14 }, hp: { base: 130, perTier: 35 }, mana: { base: 0, perTier: 0 }, crit: { base: 4, perTier: 0.6 }, block: { base: 3, perTier: 0.8 }, defense: { base: 20, perTier: 6 } }, skills: { hotkey1: { name: 'Rending Chop', description: 'Single target, applies Bleed stack' }, hotkey2: [{ name: 'Adrenaline Surge', description: '+atk speed buff' }, { name: 'Whirl of Pain', description: 'Channeled AoE' }, { name: 'Bloodletting', description: 'AoE bleed apply' }], hotkey3: [{ name: 'Blood Harvest', description: 'Lifesteal AoE' }, { name: 'Frenzied Chop', description: 'Burst self-dmg' }, { name: 'Bonehew', description: 'Armor break' }, { name: 'Shatterstrike', description: 'AoE shatter' }], hotkey4: { name: 'Carnage Spin', description: 'Refresh bleed' }, passive: [{ name: 'Life Leech', description: 'Heal on hit' }, { name: 'Vicious Wounds', description: 'Slow on bleed' }, { name: 'Slow Poison', description: '+slow duration' }] } },
      { id: 'axe_ironmaw', name: 'Ironmaw', lore: 'Maw of iron that crushes oaths', stats: { damage: { base: 61, perTier: 15 }, hp: { base: 115, perTier: 29 }, mana: { base: 5, perTier: 3 }, crit: { base: 2, perTier: 0.4 }, block: { base: 6, perTier: 1.3 }, defense: { base: 28, perTier: 8 } }, skills: { hotkey1: { name: 'Rending Chop', description: 'Single target, applies Bleed stack' }, hotkey2: [{ name: 'Lunging Chop', description: 'Range attack' }, { name: 'War Cry', description: '+dmg buff' }, { name: 'Ground Slam', description: 'AoE slow' }], hotkey3: [{ name: 'Ground Rend', description: 'Slow AoE' }, { name: 'Iron Bite', description: 'Defense ignore' }, { name: 'Dreadcleaver', description: 'Frenzy' }], hotkey4: { name: 'Reaping Slash', description: 'Massive AoE' }, passive: [{ name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Life Leech', description: 'Heal on hit' }, { name: 'Heavy Hitter', description: '+dmg' }] } },
      { id: 'axe_gorewraith', name: 'Gorewraith', lore: 'Wraith of gore and vengeance', stats: { damage: { base: 59, perTier: 14 }, hp: { base: 100, perTier: 25 }, mana: { base: 15, perTier: 8 }, crit: { base: 5, perTier: 0.7 }, block: { base: 4, perTier: 1 }, defense: { base: 22, perTier: 7 } }, skills: { hotkey1: { name: 'Rending Chop', description: 'Single target, applies Bleed stack' }, hotkey2: [{ name: 'Adrenaline Surge', description: '+atk speed buff' }, { name: 'Whirl of Pain', description: 'Channeled AoE' }, { name: 'Bloodletting', description: 'AoE bleed apply' }], hotkey3: [{ name: 'Shadow Chop', description: 'Dash + dmg' }, { name: 'Wraith Spin', description: 'AoE silence' }, { name: 'Phantom Slash', description: 'Pierce armor' }], hotkey4: { name: 'Gorewraith Fury', description: 'AoE lifesteal burst' }, passive: [{ name: 'Life Leech', description: 'Heal on hit' }, { name: 'Attack Speed', description: '+atk speed' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'axe_emberaxe', name: 'Emberaxe', lore: 'Burning with ember rage', stats: { damage: { base: 63, perTier: 16 }, hp: { base: 105, perTier: 26 }, mana: { base: 20, perTier: 10 }, crit: { base: 3, perTier: 0.5 }, block: { base: 5, perTier: 1.1 }, defense: { base: 24, perTier: 7 } }, skills: { hotkey1: { name: 'Rending Chop', description: 'Single target, applies Bleed stack' }, hotkey2: [{ name: 'Adrenaline Surge', description: '+atk speed buff' }, { name: 'Whirl of Pain', description: 'Channeled AoE' }, { name: 'Bloodletting', description: 'AoE bleed apply' }], hotkey3: [{ name: 'Flame Chop', description: 'Apply burn' }, { name: 'Ember Spin', description: 'AoE burn' }, { name: 'Ignite Bleed', description: 'Bleed + burn' }], hotkey4: { name: 'Ember Cataclysm', description: 'Fire nova burst' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Life Leech', description: 'Heal on hit' }] } }
    ]
  },
  BOW: {
    id: 'BOW',
    name: 'Bow',
    icon: '🏹',
    category: 'ranged',
    weapons: [
      { id: 'bow_grudgebow', name: 'Grudgebow', lore: 'Bow of ancient grudges', stats: { damage: { base: 45, perTier: 11 }, hp: { base: 70, perTier: 18 }, mana: { base: 30, perTier: 15 }, crit: { base: 8, perTier: 1.2 }, block: { base: 0, perTier: 0 }, defense: { base: 10, perTier: 3 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast arrow, builds Focus stack' }, hotkey2: [{ name: 'Aimed Shot', description: 'High damage single target' }, { name: 'Volley', description: 'AoE arrow rain' }, { name: 'Evasive Roll', description: 'Dodge + reposition' }], hotkey3: [{ name: 'Fire Arrow', description: 'Burn DoT' }, { name: 'Frost Arrow', description: 'Slow target' }, { name: 'Poison Arrow', description: 'Poison DoT' }], hotkey4: { name: 'Arrow Rain', description: 'Large AoE arrow storm' }, passive: [{ name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Attack Speed', description: '+atk speed' }, { name: 'Range Bonus', description: '+range' }] } },
      { id: 'bow_wraithbow', name: 'Wraithbow', lore: 'Silent arrows from shadow', stats: { damage: { base: 48, perTier: 12 }, hp: { base: 60, perTier: 15 }, mana: { base: 40, perTier: 20 }, crit: { base: 10, perTier: 1.5 }, block: { base: 0, perTier: 0 }, defense: { base: 8, perTier: 2 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast arrow, builds Focus stack' }, hotkey2: [{ name: 'Aimed Shot', description: 'High damage single target' }, { name: 'Volley', description: 'AoE arrow rain' }, { name: 'Evasive Roll', description: 'Dodge + reposition' }], hotkey3: [{ name: 'Shadow Arrow', description: 'Silence target' }, { name: 'Wraith Pierce', description: 'Pierce armor' }, { name: 'Fear Shot', description: 'Fear target' }], hotkey4: { name: 'Phantom Volley', description: 'Ghost arrows pierce all' }, passive: [{ name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Life Leech', description: 'Heal on crit' }, { name: 'Stealth Bonus', description: '+stealth dmg' }] } },
      { id: 'bow_bloodbow', name: 'Bloodbow', lore: 'Drips with enemy blood', stats: { damage: { base: 46, perTier: 11 }, hp: { base: 80, perTier: 20 }, mana: { base: 25, perTier: 12 }, crit: { base: 7, perTier: 1 }, block: { base: 0, perTier: 0 }, defense: { base: 12, perTier: 4 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast arrow, builds Focus stack' }, hotkey2: [{ name: 'Aimed Shot', description: 'High damage single target' }, { name: 'Volley', description: 'AoE arrow rain' }, { name: 'Evasive Roll', description: 'Dodge + reposition' }], hotkey3: [{ name: 'Bleed Arrow', description: 'Apply bleed' }, { name: 'Blood Volley', description: 'AoE bleed' }, { name: 'Lifesteal Shot', description: 'Heal on hit' }], hotkey4: { name: 'Blood Storm', description: 'AoE bleed rain' }, passive: [{ name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Life Leech', description: 'Heal on hit' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'bow_emberbow', name: 'Emberbow', lore: 'Arrows of burning rage', stats: { damage: { base: 47, perTier: 12 }, hp: { base: 65, perTier: 16 }, mana: { base: 35, perTier: 18 }, crit: { base: 6, perTier: 0.9 }, block: { base: 0, perTier: 0 }, defense: { base: 9, perTier: 3 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast arrow, builds Focus stack' }, hotkey2: [{ name: 'Aimed Shot', description: 'High damage single target' }, { name: 'Volley', description: 'AoE arrow rain' }, { name: 'Evasive Roll', description: 'Dodge + reposition' }], hotkey3: [{ name: 'Fire Arrow', description: 'Burn DoT' }, { name: 'Ember Volley', description: 'AoE burn' }, { name: 'Ignite Shot', description: 'Explode on hit' }], hotkey4: { name: 'Inferno Rain', description: 'AoE fire storm' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Attack Speed', description: '+atk speed' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'bow_frostbow', name: 'Frostbow', lore: 'Chilling arrows of winter', stats: { damage: { base: 44, perTier: 10 }, hp: { base: 75, perTier: 19 }, mana: { base: 45, perTier: 22 }, crit: { base: 5, perTier: 0.8 }, block: { base: 0, perTier: 0 }, defense: { base: 11, perTier: 3 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast arrow, builds Focus stack' }, hotkey2: [{ name: 'Aimed Shot', description: 'High damage single target' }, { name: 'Volley', description: 'AoE arrow rain' }, { name: 'Evasive Roll', description: 'Dodge + reposition' }], hotkey3: [{ name: 'Frost Arrow', description: 'Slow target' }, { name: 'Ice Volley', description: 'AoE slow' }, { name: 'Freeze Shot', description: 'Root target' }], hotkey4: { name: 'Blizzard Rain', description: 'AoE freeze storm' }, passive: [{ name: 'Slow Mastery', description: '+slow duration' }, { name: 'Mana Regen', description: '+mana regen' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'bow_stormbow', name: 'Stormbow', lore: 'Arrows of thunder and lightning', stats: { damage: { base: 49, perTier: 12 }, hp: { base: 55, perTier: 14 }, mana: { base: 50, perTier: 25 }, crit: { base: 9, perTier: 1.3 }, block: { base: 0, perTier: 0 }, defense: { base: 7, perTier: 2 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast arrow, builds Focus stack' }, hotkey2: [{ name: 'Aimed Shot', description: 'High damage single target' }, { name: 'Volley', description: 'AoE arrow rain' }, { name: 'Evasive Roll', description: 'Dodge + reposition' }], hotkey3: [{ name: 'Lightning Arrow', description: 'Chain to nearby enemies' }, { name: 'Thunder Volley', description: 'AoE stun chance' }, { name: 'Shock Shot', description: 'Interrupt cast' }], hotkey4: { name: 'Storm Barrage', description: 'AoE chain lightning arrows' }, passive: [{ name: 'Shock Mastery', description: '+shock dmg' }, { name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Attack Speed', description: '+atk speed' }] } }
    ]
  },
  CROSSBOW: {
    id: 'CROSSBOW',
    name: 'Crossbow',
    icon: '🎯',
    category: 'ranged',
    weapons: [
      { id: 'crossbow_grudge', name: 'Grudge Crossbow', lore: 'Heavy bolts of vengeance', stats: { damage: { base: 55, perTier: 14 }, hp: { base: 80, perTier: 20 }, mana: { base: 20, perTier: 10 }, crit: { base: 6, perTier: 0.9 }, block: { base: 2, perTier: 0.5 }, defense: { base: 15, perTier: 5 } }, skills: { hotkey1: { name: 'Heavy Bolt', description: 'Slow powerful shot' }, hotkey2: [{ name: 'Piercing Bolt', description: 'Armor pierce' }, { name: 'Explosive Bolt', description: 'AoE on hit' }, { name: 'Quick Reload', description: 'Speed buff' }], hotkey3: [{ name: 'Fire Bolt', description: 'Burn DoT' }, { name: 'Poison Bolt', description: 'Poison DoT' }, { name: 'Net Bolt', description: 'Root target' }], hotkey4: { name: 'Volley Barrage', description: 'Rapid fire burst' }, passive: [{ name: 'Armor Pen', description: '+armor pierce' }, { name: 'Crit Dmg', description: '+crit dmg' }, { name: 'Reload Speed', description: '+atk speed' }] } },
      { id: 'crossbow_repeater', name: 'Repeater Crossbow', lore: 'Rapid fire mechanism', stats: { damage: { base: 40, perTier: 10 }, hp: { base: 70, perTier: 18 }, mana: { base: 25, perTier: 12 }, crit: { base: 8, perTier: 1.2 }, block: { base: 1, perTier: 0.3 }, defense: { base: 12, perTier: 4 } }, skills: { hotkey1: { name: 'Rapid Fire', description: 'Fast multi-shot' }, hotkey2: [{ name: 'Piercing Bolt', description: 'Armor pierce' }, { name: 'Explosive Bolt', description: 'AoE on hit' }, { name: 'Quick Reload', description: 'Speed buff' }], hotkey3: [{ name: 'Barrage', description: 'Multi target' }, { name: 'Suppressing Fire', description: 'Slow enemies' }, { name: 'Pin Down', description: 'Root target' }], hotkey4: { name: 'Lead Storm', description: 'Channel rapid fire' }, passive: [{ name: 'Attack Speed', description: '+atk speed' }, { name: 'Crit Chance', description: '+crit' }, { name: 'Reload Speed', description: '+reload' }] } },
      { id: 'crossbow_siege', name: 'Siege Crossbow', lore: 'Heavy siege weapon', stats: { damage: { base: 65, perTier: 17 }, hp: { base: 90, perTier: 23 }, mana: { base: 15, perTier: 8 }, crit: { base: 4, perTier: 0.6 }, block: { base: 3, perTier: 0.8 }, defense: { base: 18, perTier: 6 } }, skills: { hotkey1: { name: 'Siege Bolt', description: 'Massive damage shot' }, hotkey2: [{ name: 'Piercing Bolt', description: 'Armor pierce' }, { name: 'Explosive Bolt', description: 'AoE on hit' }, { name: 'Quick Reload', description: 'Speed buff' }], hotkey3: [{ name: 'Demolish', description: 'Armor break' }, { name: 'Wall Breaker', description: 'Pierce shields' }, { name: 'Impact', description: 'Knockback' }], hotkey4: { name: 'Ballista Shot', description: 'Massive pierce all' }, passive: [{ name: 'Armor Pen', description: '+armor pierce' }, { name: 'Heavy Hitter', description: '+dmg' }, { name: 'Knockback', description: '+knockback' }] } },
      { id: 'crossbow_shadow', name: 'Shadow Crossbow', lore: 'Silent assassin bolts', stats: { damage: { base: 50, perTier: 13 }, hp: { base: 60, perTier: 15 }, mana: { base: 35, perTier: 18 }, crit: { base: 10, perTier: 1.5 }, block: { base: 0, perTier: 0 }, defense: { base: 10, perTier: 3 } }, skills: { hotkey1: { name: 'Shadow Bolt', description: 'Silent shot' }, hotkey2: [{ name: 'Piercing Bolt', description: 'Armor pierce' }, { name: 'Explosive Bolt', description: 'AoE on hit' }, { name: 'Quick Reload', description: 'Speed buff' }], hotkey3: [{ name: 'Poison Bolt', description: 'DoT' }, { name: 'Silence Bolt', description: 'Silence target' }, { name: 'Fear Bolt', description: 'Fear target' }], hotkey4: { name: 'Assassinate', description: 'Execute low HP' }, passive: [{ name: 'Stealth Dmg', description: '+stealth dmg' }, { name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Life Leech', description: 'Heal on crit' }] } },
      { id: 'crossbow_ember', name: 'Ember Crossbow', lore: 'Burning bolts of fire', stats: { damage: { base: 52, perTier: 13 }, hp: { base: 75, perTier: 19 }, mana: { base: 30, perTier: 15 }, crit: { base: 7, perTier: 1 }, block: { base: 1, perTier: 0.3 }, defense: { base: 13, perTier: 4 } }, skills: { hotkey1: { name: 'Fire Bolt', description: 'Burn on hit' }, hotkey2: [{ name: 'Piercing Bolt', description: 'Armor pierce' }, { name: 'Explosive Bolt', description: 'AoE on hit' }, { name: 'Quick Reload', description: 'Speed buff' }], hotkey3: [{ name: 'Inferno Bolt', description: 'Large burn' }, { name: 'Ember Spray', description: 'Cone fire' }, { name: 'Ignite', description: 'Explode burns' }], hotkey4: { name: 'Firestorm Volley', description: 'AoE fire rain' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Crit Chance', description: '+crit' }, { name: 'Attack Speed', description: '+atk speed' }] } },
      { id: 'crossbow_frost', name: 'Frost Crossbow', lore: 'Freezing bolts of ice', stats: { damage: { base: 48, perTier: 12 }, hp: { base: 85, perTier: 21 }, mana: { base: 40, perTier: 20 }, crit: { base: 5, perTier: 0.8 }, block: { base: 2, perTier: 0.5 }, defense: { base: 16, perTier: 5 } }, skills: { hotkey1: { name: 'Ice Bolt', description: 'Slow on hit' }, hotkey2: [{ name: 'Piercing Bolt', description: 'Armor pierce' }, { name: 'Explosive Bolt', description: 'AoE on hit' }, { name: 'Quick Reload', description: 'Speed buff' }], hotkey3: [{ name: 'Freeze Bolt', description: 'Root target' }, { name: 'Ice Spray', description: 'Cone slow' }, { name: 'Shatter', description: 'Break frozen' }], hotkey4: { name: 'Blizzard Volley', description: 'AoE freeze storm' }, passive: [{ name: 'Slow Mastery', description: '+slow duration' }, { name: 'Freeze Duration', description: '+freeze time' }, { name: 'Mana Regen', description: '+mana regen' }] } }
    ]
  },
  DAGGER: {
    id: 'DAGGER',
    name: 'Dagger',
    icon: '🗡️',
    category: 'melee',
    weapons: [
      { id: 'dagger_grudge', name: 'Grudge Dagger', lore: 'Quick strikes of vengeance', stats: { damage: { base: 35, perTier: 9 }, hp: { base: 60, perTier: 15 }, mana: { base: 40, perTier: 20 }, crit: { base: 12, perTier: 1.8 }, block: { base: 3, perTier: 0.8 }, defense: { base: 8, perTier: 2 } }, skills: { hotkey1: { name: 'Quick Stab', description: 'Fast attack, builds Combo' }, hotkey2: [{ name: 'Backstab', description: 'Bonus from behind' }, { name: 'Shadowstep', description: 'Teleport behind' }, { name: 'Evade', description: 'Dodge attack' }], hotkey3: [{ name: 'Poison Blade', description: 'Apply poison' }, { name: 'Bleed Strike', description: 'Apply bleed' }, { name: 'Cripple', description: 'Slow target' }], hotkey4: { name: 'Death Blossom', description: 'AoE spin attack' }, passive: [{ name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Attack Speed', description: '+atk speed' }, { name: 'Stealth Dmg', description: '+stealth dmg' }] } },
      { id: 'dagger_shadow', name: 'Shadow Dagger', lore: 'Strike from darkness', stats: { damage: { base: 38, perTier: 10 }, hp: { base: 50, perTier: 12 }, mana: { base: 50, perTier: 25 }, crit: { base: 15, perTier: 2.2 }, block: { base: 2, perTier: 0.5 }, defense: { base: 6, perTier: 1.5 } }, skills: { hotkey1: { name: 'Quick Stab', description: 'Fast attack, builds Combo' }, hotkey2: [{ name: 'Backstab', description: 'Bonus from behind' }, { name: 'Shadowstep', description: 'Teleport behind' }, { name: 'Evade', description: 'Dodge attack' }], hotkey3: [{ name: 'Shadow Strike', description: 'Silence target' }, { name: 'Dark Blade', description: 'Fear on hit' }, { name: 'Vanish', description: 'Stealth' }], hotkey4: { name: 'Shadow Dance', description: 'Multi-target stealth attacks' }, passive: [{ name: 'Stealth Mastery', description: '+stealth duration' }, { name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Life Leech', description: 'Heal on crit' }] } },
      { id: 'dagger_poison', name: 'Poison Dagger', lore: 'Coated in deadly venom', stats: { damage: { base: 33, perTier: 8 }, hp: { base: 55, perTier: 14 }, mana: { base: 45, perTier: 22 }, crit: { base: 10, perTier: 1.5 }, block: { base: 2, perTier: 0.5 }, defense: { base: 7, perTier: 2 } }, skills: { hotkey1: { name: 'Quick Stab', description: 'Fast attack, builds Combo' }, hotkey2: [{ name: 'Backstab', description: 'Bonus from behind' }, { name: 'Shadowstep', description: 'Teleport behind' }, { name: 'Evade', description: 'Dodge attack' }], hotkey3: [{ name: 'Toxic Stab', description: 'Strong poison' }, { name: 'Venom Spray', description: 'AoE poison' }, { name: 'Paralyze', description: 'Stun target' }], hotkey4: { name: 'Plague Strike', description: 'Spread poison to all' }, passive: [{ name: 'Poison Mastery', description: '+poison dmg' }, { name: 'Poison Duration', description: '+poison time' }, { name: 'Attack Speed', description: '+atk speed' }] } },
      { id: 'dagger_blood', name: 'Blood Dagger', lore: 'Drips with enemy lifeblood', stats: { damage: { base: 36, perTier: 9 }, hp: { base: 65, perTier: 16 }, mana: { base: 35, perTier: 18 }, crit: { base: 11, perTier: 1.6 }, block: { base: 3, perTier: 0.8 }, defense: { base: 9, perTier: 2.5 } }, skills: { hotkey1: { name: 'Quick Stab', description: 'Fast attack, builds Combo' }, hotkey2: [{ name: 'Backstab', description: 'Bonus from behind' }, { name: 'Shadowstep', description: 'Teleport behind' }, { name: 'Evade', description: 'Dodge attack' }], hotkey3: [{ name: 'Bleed Strike', description: 'Heavy bleed' }, { name: 'Blood Frenzy', description: 'Atk speed buff on bleed' }, { name: 'Lifesteal Stab', description: 'Heal on hit' }], hotkey4: { name: 'Crimson Flurry', description: 'Multi-hit lifesteal' }, passive: [{ name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Life Leech', description: 'Heal on hit' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'dagger_ember', name: 'Ember Dagger', lore: 'Burns with inner fire', stats: { damage: { base: 37, perTier: 9 }, hp: { base: 55, perTier: 14 }, mana: { base: 42, perTier: 21 }, crit: { base: 9, perTier: 1.4 }, block: { base: 2, perTier: 0.5 }, defense: { base: 8, perTier: 2 } }, skills: { hotkey1: { name: 'Quick Stab', description: 'Fast attack, builds Combo' }, hotkey2: [{ name: 'Backstab', description: 'Bonus from behind' }, { name: 'Shadowstep', description: 'Teleport behind' }, { name: 'Evade', description: 'Dodge attack' }], hotkey3: [{ name: 'Fire Stab', description: 'Apply burn' }, { name: 'Ember Dash', description: 'Dash + burn trail' }, { name: 'Ignite', description: 'Explode burns' }], hotkey4: { name: 'Inferno Dance', description: 'AoE fire spin' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Attack Speed', description: '+atk speed' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'dagger_frost', name: 'Frost Dagger', lore: 'Chilling touch of death', stats: { damage: { base: 34, perTier: 8 }, hp: { base: 60, perTier: 15 }, mana: { base: 48, perTier: 24 }, crit: { base: 8, perTier: 1.2 }, block: { base: 3, perTier: 0.8 }, defense: { base: 10, perTier: 3 } }, skills: { hotkey1: { name: 'Quick Stab', description: 'Fast attack, builds Combo' }, hotkey2: [{ name: 'Backstab', description: 'Bonus from behind' }, { name: 'Shadowstep', description: 'Teleport behind' }, { name: 'Evade', description: 'Dodge attack' }], hotkey3: [{ name: 'Frost Stab', description: 'Apply slow' }, { name: 'Ice Dash', description: 'Dash + freeze' }, { name: 'Shatter', description: 'Break frozen' }], hotkey4: { name: 'Frozen Flurry', description: 'Multi-hit freeze' }, passive: [{ name: 'Slow Mastery', description: '+slow duration' }, { name: 'Freeze Duration', description: '+freeze time' }, { name: 'Crit Chance', description: '+crit' }] } }
    ]
  },
  GUN: {
    id: 'GUN',
    name: 'Gun',
    icon: '🔫',
    category: 'ranged',
    weapons: [
      { id: 'gun_grudge', name: 'Grudge Pistol', lore: 'Quick-draw vengeance', stats: { damage: { base: 42, perTier: 11 }, hp: { base: 65, perTier: 16 }, mana: { base: 30, perTier: 15 }, crit: { base: 10, perTier: 1.5 }, block: { base: 2, perTier: 0.5 }, defense: { base: 10, perTier: 3 } }, skills: { hotkey1: { name: 'Quick Shot', description: 'Fast pistol shot' }, hotkey2: [{ name: 'Fan the Hammer', description: 'Rapid fire' }, { name: 'Aimed Shot', description: 'High damage single' }, { name: 'Roll', description: 'Dodge + reload' }], hotkey3: [{ name: 'Incendiary', description: 'Fire bullet' }, { name: 'Explosive', description: 'AoE bullet' }, { name: 'Piercing', description: 'Armor pierce' }], hotkey4: { name: 'Dead Eye', description: 'Multi-target execute' }, passive: [{ name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Reload Speed', description: '+reload' }, { name: 'Attack Speed', description: '+atk speed' }] } },
      { id: 'gun_blunderbuss', name: 'Blunderbuss', lore: 'Devastating close range', stats: { damage: { base: 60, perTier: 15 }, hp: { base: 75, perTier: 19 }, mana: { base: 20, perTier: 10 }, crit: { base: 5, perTier: 0.8 }, block: { base: 3, perTier: 0.8 }, defense: { base: 14, perTier: 4 } }, skills: { hotkey1: { name: 'Buckshot', description: 'Cone damage' }, hotkey2: [{ name: 'Fan the Hammer', description: 'Rapid fire' }, { name: 'Aimed Shot', description: 'High damage single' }, { name: 'Roll', description: 'Dodge + reload' }], hotkey3: [{ name: 'Scatter Shot', description: 'Wide cone' }, { name: 'Grapeshot', description: 'Multi-pellet' }, { name: 'Knockback', description: 'Push enemies' }], hotkey4: { name: 'Point Blank', description: 'Massive close range' }, passive: [{ name: 'Spread Mastery', description: '+cone width' }, { name: 'Heavy Hitter', description: '+dmg' }, { name: 'Knockback Force', description: '+knockback' }] } },
      { id: 'gun_rifle', name: 'Hunting Rifle', lore: 'Long range precision', stats: { damage: { base: 55, perTier: 14 }, hp: { base: 60, perTier: 15 }, mana: { base: 25, perTier: 12 }, crit: { base: 12, perTier: 1.8 }, block: { base: 1, perTier: 0.3 }, defense: { base: 8, perTier: 2 } }, skills: { hotkey1: { name: 'Precision Shot', description: 'High accuracy' }, hotkey2: [{ name: 'Fan the Hammer', description: 'Rapid fire' }, { name: 'Aimed Shot', description: 'High damage single' }, { name: 'Roll', description: 'Dodge + reload' }], hotkey3: [{ name: 'Headshot', description: 'Execute low HP' }, { name: 'Suppress', description: 'Slow target' }, { name: 'Mark Target', description: 'Bonus dmg' }], hotkey4: { name: 'Sniper Shot', description: 'Massive single target' }, passive: [{ name: 'Range Bonus', description: '+range' }, { name: 'Crit Mastery', description: '+crit dmg' }, { name: 'Accuracy', description: '+hit chance' }] } },
      { id: 'gun_musket', name: 'Musket', lore: 'Heavy firepower', stats: { damage: { base: 58, perTier: 15 }, hp: { base: 70, perTier: 18 }, mana: { base: 22, perTier: 11 }, crit: { base: 8, perTier: 1.2 }, block: { base: 2, perTier: 0.5 }, defense: { base: 12, perTier: 4 } }, skills: { hotkey1: { name: 'Heavy Shot', description: 'Powerful shot' }, hotkey2: [{ name: 'Fan the Hammer', description: 'Rapid fire' }, { name: 'Aimed Shot', description: 'High damage single' }, { name: 'Roll', description: 'Dodge + reload' }], hotkey3: [{ name: 'Bayonet', description: 'Melee attack' }, { name: 'Volley', description: 'AoE line' }, { name: 'Powder Keg', description: 'AoE explosion' }], hotkey4: { name: 'Cannon Blast', description: 'Massive AoE' }, passive: [{ name: 'Heavy Hitter', description: '+dmg' }, { name: 'Armor Pen', description: '+armor pierce' }, { name: 'Reload Speed', description: '+reload' }] } },
      { id: 'gun_ember', name: 'Ember Pistol', lore: 'Fire-enchanted shots', stats: { damage: { base: 44, perTier: 11 }, hp: { base: 60, perTier: 15 }, mana: { base: 35, perTier: 18 }, crit: { base: 9, perTier: 1.4 }, block: { base: 2, perTier: 0.5 }, defense: { base: 9, perTier: 2.5 } }, skills: { hotkey1: { name: 'Fire Shot', description: 'Burn on hit' }, hotkey2: [{ name: 'Fan the Hammer', description: 'Rapid fire' }, { name: 'Aimed Shot', description: 'High damage single' }, { name: 'Roll', description: 'Dodge + reload' }], hotkey3: [{ name: 'Inferno Bullet', description: 'Strong burn' }, { name: 'Explosive Round', description: 'AoE fire' }, { name: 'Ignite', description: 'Explode burns' }], hotkey4: { name: 'Hellfire Barrage', description: 'Multi-target fire' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Crit Chance', description: '+crit' }, { name: 'Attack Speed', description: '+atk speed' }] } },
      { id: 'gun_frost', name: 'Frost Pistol', lore: 'Ice-enchanted shots', stats: { damage: { base: 40, perTier: 10 }, hp: { base: 68, perTier: 17 }, mana: { base: 40, perTier: 20 }, crit: { base: 7, perTier: 1.1 }, block: { base: 2, perTier: 0.5 }, defense: { base: 11, perTier: 3 } }, skills: { hotkey1: { name: 'Ice Shot', description: 'Slow on hit' }, hotkey2: [{ name: 'Fan the Hammer', description: 'Rapid fire' }, { name: 'Aimed Shot', description: 'High damage single' }, { name: 'Roll', description: 'Dodge + reload' }], hotkey3: [{ name: 'Freeze Bullet', description: 'Root target' }, { name: 'Frost Spray', description: 'Cone slow' }, { name: 'Shatter', description: 'Break frozen' }], hotkey4: { name: 'Blizzard Barrage', description: 'Multi-target freeze' }, passive: [{ name: 'Slow Mastery', description: '+slow duration' }, { name: 'Freeze Duration', description: '+freeze time' }, { name: 'Mana Regen', description: '+mana regen' }] } }
    ]
  },
  STAFF: {
    id: 'STAFF',
    name: 'Staff',
    icon: '🪄',
    category: 'magic',
    weapons: [
      { id: 'staff_fire', name: 'Fire Staff', lore: 'Blazing arcane power', stats: { damage: { base: 55, perTier: 14 }, hp: { base: 50, perTier: 12 }, mana: { base: 100, perTier: 50 }, crit: { base: 6, perTier: 0.9 }, block: { base: 0, perTier: 0 }, defense: { base: 8, perTier: 2 } }, skills: { hotkey1: { name: 'Fireball', description: 'AoE fire damage' }, hotkey2: [{ name: 'Fire Blast', description: 'Cone fire' }, { name: 'Flame Shield', description: 'Damage absorb' }, { name: 'Blink', description: 'Teleport' }], hotkey3: [{ name: 'Meteor', description: 'Large AoE' }, { name: 'Ignite', description: 'Spread burn' }, { name: 'Fire Wall', description: 'Zone denial' }], hotkey4: { name: 'Inferno', description: 'Massive AoE burn' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Spell Crit', description: '+spell crit' }, { name: 'Mana Regen', description: '+mana regen' }] } },
      { id: 'staff_frost', name: 'Frost Staff', lore: 'Chilling arcane power', stats: { damage: { base: 50, perTier: 13 }, hp: { base: 55, perTier: 14 }, mana: { base: 110, perTier: 55 }, crit: { base: 5, perTier: 0.8 }, block: { base: 0, perTier: 0 }, defense: { base: 10, perTier: 3 } }, skills: { hotkey1: { name: 'Ice Bolt', description: 'Slow on hit' }, hotkey2: [{ name: 'Frost Nova', description: 'AoE slow' }, { name: 'Ice Barrier', description: 'Damage absorb' }, { name: 'Blink', description: 'Teleport' }], hotkey3: [{ name: 'Blizzard', description: 'AoE freeze zone' }, { name: 'Shatter', description: 'Break frozen' }, { name: 'Ice Wall', description: 'Zone denial' }], hotkey4: { name: 'Frozen Tomb', description: 'Massive AoE freeze' }, passive: [{ name: 'Slow Mastery', description: '+slow duration' }, { name: 'Freeze Duration', description: '+freeze time' }, { name: 'Mana Regen', description: '+mana regen' }] } },
      { id: 'staff_lightning', name: 'Lightning Staff', lore: 'Crackling storm power', stats: { damage: { base: 58, perTier: 15 }, hp: { base: 45, perTier: 11 }, mana: { base: 95, perTier: 48 }, crit: { base: 8, perTier: 1.2 }, block: { base: 0, perTier: 0 }, defense: { base: 7, perTier: 2 } }, skills: { hotkey1: { name: 'Lightning Bolt', description: 'Chain to nearby' }, hotkey2: [{ name: 'Chain Lightning', description: 'Multi-target chain' }, { name: 'Storm Shield', description: 'Reflect + absorb' }, { name: 'Blink', description: 'Teleport' }], hotkey3: [{ name: 'Thunder Strike', description: 'Stun target' }, { name: 'Static Field', description: 'Zone slow' }, { name: 'Overcharge', description: 'Buff next spell' }], hotkey4: { name: 'Thunderstorm', description: 'Massive AoE chain' }, passive: [{ name: 'Shock Mastery', description: '+shock dmg' }, { name: 'Spell Crit', description: '+spell crit' }, { name: 'Cast Speed', description: '+cast speed' }] } },
      { id: 'staff_arcane', name: 'Arcane Staff', lore: 'Pure arcane energy', stats: { damage: { base: 52, perTier: 13 }, hp: { base: 60, perTier: 15 }, mana: { base: 120, perTier: 60 }, crit: { base: 7, perTier: 1.1 }, block: { base: 0, perTier: 0 }, defense: { base: 9, perTier: 2.5 } }, skills: { hotkey1: { name: 'Arcane Bolt', description: 'Pure magic damage' }, hotkey2: [{ name: 'Arcane Blast', description: 'AoE magic' }, { name: 'Mana Shield', description: 'Absorb with mana' }, { name: 'Blink', description: 'Teleport' }], hotkey3: [{ name: 'Arcane Orb', description: 'Explode on contact' }, { name: 'Time Warp', description: 'Slow enemies' }, { name: 'Amplify', description: 'Buff next spell' }], hotkey4: { name: 'Arcane Annihilation', description: 'Massive AoE nuke' }, passive: [{ name: 'Spell Power', description: '+spell dmg' }, { name: 'Mana Efficiency', description: '-mana cost' }, { name: 'Cooldown Reduce', description: '-cooldowns' }] } },
      { id: 'staff_holy', name: 'Holy Staff', lore: 'Divine healing light', stats: { damage: { base: 40, perTier: 10 }, hp: { base: 80, perTier: 20 }, mana: { base: 130, perTier: 65 }, crit: { base: 4, perTier: 0.6 }, block: { base: 0, perTier: 0 }, defense: { base: 15, perTier: 5 } }, skills: { hotkey1: { name: 'Holy Bolt', description: 'Heal ally or damage undead' }, hotkey2: [{ name: 'Holy Nova', description: 'AoE heal + damage' }, { name: 'Divine Shield', description: 'Invulnerability' }, { name: 'Flash', description: 'Teleport' }], hotkey3: [{ name: 'Smite', description: 'Heavy holy damage' }, { name: 'Purify', description: 'Remove debuffs' }, { name: 'Blessing', description: 'Buff ally' }], hotkey4: { name: 'Divine Intervention', description: 'Mass heal + resurrect' }, passive: [{ name: 'Heal Power', description: '+heal amount' }, { name: 'Mana Regen', description: '+mana regen' }, { name: 'Cooldown Reduce', description: '-cooldowns' }] } },
      { id: 'staff_nature', name: 'Nature Staff', lore: 'Druidic nature power', stats: { damage: { base: 45, perTier: 11 }, hp: { base: 70, perTier: 18 }, mana: { base: 115, perTier: 58 }, crit: { base: 5, perTier: 0.8 }, block: { base: 0, perTier: 0 }, defense: { base: 12, perTier: 4 } }, skills: { hotkey1: { name: 'Nature Bolt', description: 'Poison + heal' }, hotkey2: [{ name: 'Entangle', description: 'Root enemies' }, { name: 'Thorns', description: 'Reflect damage' }, { name: 'Wild Growth', description: 'HoT' }], hotkey3: [{ name: 'Poison Cloud', description: 'AoE poison zone' }, { name: 'Regrowth', description: 'Strong HoT' }, { name: 'Brambles', description: 'Zone denial' }], hotkey4: { name: 'Wrath of Nature', description: 'Massive AoE + heal' }, passive: [{ name: 'Poison Mastery', description: '+poison dmg' }, { name: 'Heal Power', description: '+heal amount' }, { name: 'Mana Regen', description: '+mana regen' }] } }
    ]
  },
  MACE: {
    id: 'MACE',
    name: 'Mace',
    icon: '🏏',
    category: 'melee',
    weapons: [
      { id: 'mace_iron', name: 'Iron Club', lore: 'Crude but effective bludgeon', stats: { damage: { base: 52, perTier: 12 }, hp: { base: 105, perTier: 26 }, mana: { base: 0, perTier: 0 }, crit: { base: 2, perTier: 0.4 }, block: { base: 7, perTier: 1.4 }, defense: { base: 24, perTier: 7 } }, skills: { hotkey1: { name: 'Bash', description: 'Single, applies Daze stack' }, hotkey2: [{ name: 'Stunning Smash', description: 'Stun single' }, { name: 'Shield Bash', description: 'Block + dmg' }, { name: 'Battle Cry', description: '+dmg buff' }], hotkey3: [{ name: 'Concussive Blow', description: 'Slow AoE' }, { name: 'Crushing Strike', description: 'Armor reduce' }, { name: 'Skull Crack', description: 'Silence' }], hotkey4: { name: 'Bonecrusher', description: 'Massive single stun' }, passive: [{ name: 'Stun Mastery', description: '+stun duration' }, { name: 'Heavy Blows', description: '+dmg' }, { name: 'Resilience', description: '+defense' }] } },
      { id: 'mace_steel', name: 'Steel Mace', lore: 'Balanced weight for precise strikes', stats: { damage: { base: 55, perTier: 13 }, hp: { base: 110, perTier: 28 }, mana: { base: 10, perTier: 5 }, crit: { base: 3, perTier: 0.5 }, block: { base: 8, perTier: 1.5 }, defense: { base: 26, perTier: 8 } }, skills: { hotkey1: { name: 'Bash', description: 'Single, applies Daze stack' }, hotkey2: [{ name: 'Stunning Smash', description: 'Stun single' }, { name: 'Shield Bash', description: 'Block + dmg' }, { name: 'Battle Cry', description: '+dmg buff' }], hotkey3: [{ name: 'Power Swing', description: 'Burst dmg' }, { name: 'Armor Breaker', description: 'Def reduce' }, { name: 'Ground Pound', description: 'AoE slow' }], hotkey4: { name: 'Shattering Blow', description: 'Armor break burst' }, passive: [{ name: 'Heavy Blows', description: '+dmg' }, { name: 'Block Mastery', description: '+block' }, { name: 'Slow on Hit', description: 'Slow enemies' }] } },
      { id: 'mace_flanged', name: 'Flanged Death', lore: 'Flanged head tears through armor', stats: { damage: { base: 58, perTier: 14 }, hp: { base: 100, perTier: 25 }, mana: { base: 15, perTier: 8 }, crit: { base: 4, perTier: 0.6 }, block: { base: 6, perTier: 1.2 }, defense: { base: 22, perTier: 6 } }, skills: { hotkey1: { name: 'Bash', description: 'Single, applies Daze stack' }, hotkey2: [{ name: 'Rending Smash', description: 'Bleed apply' }, { name: 'Flange Sweep', description: 'Cone AoE' }, { name: 'Adrenaline Rush', description: '+atk speed' }], hotkey3: [{ name: 'Crimson Bash', description: 'Bleed burst' }, { name: 'Flesh Ripper', description: 'Spread bleed' }, { name: 'Savage Strike', description: 'Crit boost' }], hotkey4: { name: 'Tearing Blow', description: 'Massive bleed' }, passive: [{ name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Life Leech', description: 'Heal on hit' }, { name: 'Crit Chance', description: '+crit' }] } },
      { id: 'mace_morning', name: 'Morning Star', lore: 'Spiked ball of righteous pain', stats: { damage: { base: 56, perTier: 13 }, hp: { base: 115, perTier: 30 }, mana: { base: 20, perTier: 10 }, crit: { base: 5, perTier: 0.7 }, block: { base: 5, perTier: 1.1 }, defense: { base: 20, perTier: 6 } }, skills: { hotkey1: { name: 'Bash', description: 'Single, applies Daze stack' }, hotkey2: [{ name: 'Stunning Smash', description: 'Stun single' }, { name: 'Shield Bash', description: 'Block + dmg' }, { name: 'Battle Cry', description: '+dmg buff' }], hotkey3: [{ name: 'Piercing Smash', description: 'Ignore def' }, { name: 'Chain Swing', description: 'Multi hit' }, { name: 'Impale Spike', description: 'Root' }, { name: 'Star Burst', description: 'AoE' }], hotkey4: { name: 'Morning Wrath', description: 'AoE stun + bleed' }, passive: [{ name: 'Stun Mastery', description: '+stun duration' }, { name: 'Piercing Blows', description: 'Armor pen' }, { name: 'Attack Speed', description: '+atk speed' }] } },
      { id: 'mace_shadow', name: 'Shadowflail', lore: 'Flail wrapped in dark energy', stats: { damage: { base: 54, perTier: 13 }, hp: { base: 95, perTier: 24 }, mana: { base: 25, perTier: 12 }, crit: { base: 6, perTier: 0.8 }, block: { base: 4, perTier: 1 }, defense: { base: 18, perTier: 5 } }, skills: { hotkey1: { name: 'Bash', description: 'Single, applies Daze stack' }, hotkey2: [{ name: 'Shadow Smash', description: 'Silence' }, { name: 'Phase Swing', description: 'Teleport + dmg' }, { name: 'Dark Aura', description: 'Fear aura' }], hotkey3: [{ name: 'Phantom Chain', description: 'Multi silence' }, { name: 'Void Strike', description: 'Ignore def' }, { name: 'Shadow Pull', description: 'Gap close' }], hotkey4: { name: 'Umbral Devastation', description: 'AoE fear + silence' }, passive: [{ name: 'Slow Poison', description: 'Slow on hit' }, { name: 'Cooldown Reduce', description: '-cooldowns' }, { name: 'Phase Strike', description: '+pierce' }] } },
      { id: 'mace_holy', name: 'Holy Scepter', lore: 'Divine authority made manifest', stats: { damage: { base: 50, perTier: 12 }, hp: { base: 120, perTier: 32 }, mana: { base: 30, perTier: 15 }, crit: { base: 3, perTier: 0.5 }, block: { base: 9, perTier: 1.8 }, defense: { base: 28, perTier: 9 } }, skills: { hotkey1: { name: 'Bash', description: 'Single, applies Daze stack' }, hotkey2: [{ name: 'Holy Smash', description: 'Heal on hit' }, { name: 'Divine Shield', description: 'Absorb' }, { name: 'Blessing Aura', description: '+party buff' }], hotkey3: [{ name: 'Smite', description: 'Holy burst' }, { name: 'Purifying Strike', description: 'Cleanse' }, { name: 'Consecrated Blow', description: 'AoE holy' }], hotkey4: { name: 'Divine Judgment', description: 'Massive holy AoE + heal' }, passive: [{ name: 'Holy Dmg', description: '+holy' }, { name: 'Heal on Hit', description: 'Self heal' }, { name: 'Resilience', description: '+defense' }] } }
    ]
  },
  LANCE: {
    id: 'LANCE',
    name: 'Lance',
    icon: '🔱',
    category: 'melee',
    weapons: [
      { id: 'lance_iron', name: 'Iron Pike', lore: 'First forged pike of the clans', stats: { damage: { base: 58, perTier: 14 }, hp: { base: 110, perTier: 28 }, mana: { base: 0, perTier: 0 }, crit: { base: 3, perTier: 0.5 }, block: { base: 6, perTier: 1.2 }, defense: { base: 22, perTier: 7 } }, skills: { hotkey1: { name: 'Thrust', description: 'Long-range single, builds Impale Mark' }, hotkey2: [{ name: 'Cavalry Charge', description: 'Dash pierce AoE' }, { name: 'Deflecting Guard', description: 'Block + counter' }, { name: 'Phalanx Stance', description: '+defense buff' }], hotkey3: [{ name: 'Skewer', description: 'Multi-target pierce' }, { name: 'Leg Sweep', description: 'AoE knockdown' }, { name: 'Pinning Strike', description: 'Root single' }], hotkey4: { name: 'Impaling Rush', description: 'Charge + massive pierce' }, passive: [{ name: 'First Strike', description: '+dmg on opener' }, { name: 'Reach Mastery', description: '+range' }, { name: 'Armor Pierce', description: 'Ignore 15% def' }] } },
      { id: 'lance_steel', name: 'Steel Lance', lore: 'Refined steel for mounted combat', stats: { damage: { base: 62, perTier: 15 }, hp: { base: 115, perTier: 30 }, mana: { base: 10, perTier: 5 }, crit: { base: 4, perTier: 0.6 }, block: { base: 7, perTier: 1.4 }, defense: { base: 24, perTier: 8 } }, skills: { hotkey1: { name: 'Thrust', description: 'Long-range single, builds Impale Mark' }, hotkey2: [{ name: 'Cavalry Charge', description: 'Dash pierce AoE' }, { name: 'Deflecting Guard', description: 'Block + counter' }, { name: 'Phalanx Stance', description: '+defense buff' }], hotkey3: [{ name: 'Lunging Thrust', description: 'Extended range' }, { name: 'Shield Break', description: 'Armor reduce' }, { name: 'Sweeping Arc', description: 'Cone AoE' }], hotkey4: { name: 'Jousting Strike', description: 'Massive charge burst' }, passive: [{ name: 'Reach Mastery', description: '+range' }, { name: 'Heavy Hitter', description: '+dmg' }, { name: 'Block Mastery', description: '+block chance' }] } },
      { id: 'lance_mithril', name: 'Mithril Javelin', lore: 'Light as air, sharp as grudge', stats: { damage: { base: 55, perTier: 13 }, hp: { base: 90, perTier: 22 }, mana: { base: 25, perTier: 12 }, crit: { base: 6, perTier: 0.9 }, block: { base: 4, perTier: 1 }, defense: { base: 18, perTier: 5 } }, skills: { hotkey1: { name: 'Thrust', description: 'Long-range single, builds Impale Mark' }, hotkey2: [{ name: 'Javelin Throw', description: 'Ranged single' }, { name: 'Quick Jab', description: 'Fast attack' }, { name: 'Evasive Stance', description: 'Dodge buff' }], hotkey3: [{ name: 'Piercing Rain', description: 'AoE thrown' }, { name: 'Shadow Thrust', description: 'Silence pierce' }, { name: 'Multi-Jab', description: 'Rapid combo' }], hotkey4: { name: 'Storm of Spears', description: 'AoE rain' }, passive: [{ name: 'Swift Strikes', description: '+atk speed' }, { name: 'Precision', description: '+crit' }, { name: 'Slow Poison', description: 'Slow on hit' }] } },
      { id: 'lance_blood', name: 'Bloodspear', lore: 'Drinks deeply of enemy blood', stats: { damage: { base: 60, perTier: 15 }, hp: { base: 120, perTier: 32 }, mana: { base: 15, perTier: 8 }, crit: { base: 5, perTier: 0.7 }, block: { base: 5, perTier: 1.1 }, defense: { base: 20, perTier: 6 } }, skills: { hotkey1: { name: 'Thrust', description: 'Long-range single, builds Impale Mark' }, hotkey2: [{ name: 'Cavalry Charge', description: 'Dash pierce AoE' }, { name: 'Deflecting Guard', description: 'Block + counter' }, { name: 'Phalanx Stance', description: '+defense buff' }], hotkey3: [{ name: 'Crimson Pierce', description: 'Bleed burst' }, { name: 'Blood Thrust', description: 'Lifesteal' }, { name: 'Hemorrhage', description: 'Spread bleed' }, { name: 'Vein Ripper', description: 'Execute' }], hotkey4: { name: 'Sanguine Impale', description: 'Massive bleed' }, passive: [{ name: 'Life Leech', description: 'Heal on hit' }, { name: 'Bleed Mastery', description: '+bleed dmg' }, { name: 'Bloodlust', description: '+atk speed on kill' }] } },
      { id: 'lance_void', name: 'Voidpiercer', lore: 'Pierces the veil between worlds', stats: { damage: { base: 65, perTier: 16 }, hp: { base: 100, perTier: 25 }, mana: { base: 30, perTier: 15 }, crit: { base: 7, perTier: 1 }, block: { base: 3, perTier: 0.8 }, defense: { base: 16, perTier: 4 } }, skills: { hotkey1: { name: 'Thrust', description: 'Long-range single, builds Impale Mark' }, hotkey2: [{ name: 'Shadow Charge', description: 'Dash + silence' }, { name: 'Void Guard', description: 'Absorb + reflect' }, { name: 'Phase Stance', description: 'Invis' }], hotkey3: [{ name: 'Phantom Pierce', description: 'Ignore def' }, { name: 'Shadow Impale', description: 'Fear burst' }, { name: 'Void Step', description: 'Teleport thrust' }], hotkey4: { name: 'Dimensional Rift', description: 'Line AoE pierce' }, passive: [{ name: 'Phase Strike', description: '+pierce' }, { name: 'Void Touch', description: 'Slow on hit' }, { name: 'Cooldown Reduce', description: '-cooldowns' }] } },
      { id: 'lance_divine', name: 'Divine Trident', lore: 'Three-pronged wrath of the heavens', stats: { damage: { base: 68, perTier: 17 }, hp: { base: 130, perTier: 35 }, mana: { base: 20, perTier: 10 }, crit: { base: 4, perTier: 0.6 }, block: { base: 8, perTier: 1.6 }, defense: { base: 28, perTier: 9 } }, skills: { hotkey1: { name: 'Thrust', description: 'Long-range single, builds Impale Mark' }, hotkey2: [{ name: 'Holy Charge', description: 'Dash + heal' }, { name: 'Divine Guard', description: 'Absorb + purify' }, { name: 'Sanctified Stance', description: '+holy dmg' }], hotkey3: [{ name: 'Triple Pierce', description: '3-hit combo' }, { name: 'Smite Thrust', description: 'Holy burst' }, { name: 'Consecrate', description: 'AoE buff zone' }], hotkey4: { name: 'Wrath of Poseidon', description: 'Massive holy AoE' }, passive: [{ name: 'Holy Dmg', description: '+holy' }, { name: 'Heal on Hit', description: 'Self heal' }, { name: 'Resilience', description: '+defense' }] } }
    ]
  },
  HAMMER: {
    id: 'HAMMER',
    name: 'Hammer',
    icon: '🔨',
    category: 'melee',
    weapons: [
      { id: 'hammer_grudge', name: 'Grudge Hammer', lore: 'Crushing force of vengeance', stats: { damage: { base: 65, perTier: 17 }, hp: { base: 140, perTier: 35 }, mana: { base: 0, perTier: 0 }, crit: { base: 2, perTier: 0.3 }, block: { base: 8, perTier: 2 }, defense: { base: 35, perTier: 10 } }, skills: { hotkey1: { name: 'Crushing Blow', description: 'Heavy single hit' }, hotkey2: [{ name: 'Ground Slam', description: 'AoE stun' }, { name: 'Shield Wall', description: 'Damage reduction' }, { name: 'Charge', description: 'Gap closer' }], hotkey3: [{ name: 'Shatter Armor', description: 'Reduce defense' }, { name: 'Concussion', description: 'Stun target' }, { name: 'Tremor', description: 'AoE slow' }], hotkey4: { name: 'Cataclysm', description: 'Massive AoE knockup' }, passive: [{ name: 'Stun Mastery', description: '+stun duration' }, { name: 'Heavy Hitter', description: '+dmg' }, { name: 'Resilience', description: '+defense' }] } },
      { id: 'hammer_titan', name: 'Titan Hammer', lore: 'Titanic crushing force', stats: { damage: { base: 70, perTier: 18 }, hp: { base: 150, perTier: 38 }, mana: { base: 0, perTier: 0 }, crit: { base: 1, perTier: 0.2 }, block: { base: 10, perTier: 2.5 }, defense: { base: 40, perTier: 12 } }, skills: { hotkey1: { name: 'Crushing Blow', description: 'Heavy single hit' }, hotkey2: [{ name: 'Ground Slam', description: 'AoE stun' }, { name: 'Shield Wall', description: 'Damage reduction' }, { name: 'Charge', description: 'Gap closer' }], hotkey3: [{ name: 'Titan Strike', description: 'Massive single hit' }, { name: 'Earthshaker', description: 'Large AoE' }, { name: 'Iron Skin', description: 'Damage immunity' }], hotkey4: { name: 'World Breaker', description: 'Ultimate AoE destruction' }, passive: [{ name: 'Heavy Hitter', description: '+dmg' }, { name: 'Resilience', description: '+defense' }, { name: 'Block Mastery', description: '+block chance' }] } },
      { id: 'hammer_storm', name: 'Storm Hammer', lore: 'Thunder-infused strikes', stats: { damage: { base: 62, perTier: 16 }, hp: { base: 120, perTier: 30 }, mana: { base: 30, perTier: 15 }, crit: { base: 4, perTier: 0.6 }, block: { base: 6, perTier: 1.5 }, defense: { base: 30, perTier: 9 } }, skills: { hotkey1: { name: 'Thunder Strike', description: 'Chain lightning on hit' }, hotkey2: [{ name: 'Ground Slam', description: 'AoE stun' }, { name: 'Shield Wall', description: 'Damage reduction' }, { name: 'Charge', description: 'Gap closer' }], hotkey3: [{ name: 'Storm Slam', description: 'AoE shock' }, { name: 'Lightning Bolt', description: 'Ranged shock' }, { name: 'Overcharge', description: 'Buff next attack' }], hotkey4: { name: 'Thundergod', description: 'Massive AoE chain lightning' }, passive: [{ name: 'Shock Mastery', description: '+shock dmg' }, { name: 'Stun Duration', description: '+stun time' }, { name: 'Heavy Hitter', description: '+dmg' }] } },
      { id: 'hammer_holy', name: 'Holy Hammer', lore: 'Divine justice', stats: { damage: { base: 58, perTier: 15 }, hp: { base: 130, perTier: 33 }, mana: { base: 40, perTier: 20 }, crit: { base: 3, perTier: 0.5 }, block: { base: 7, perTier: 1.8 }, defense: { base: 32, perTier: 10 } }, skills: { hotkey1: { name: 'Holy Smash', description: 'Holy damage + heal self' }, hotkey2: [{ name: 'Ground Slam', description: 'AoE stun' }, { name: 'Shield Wall', description: 'Damage reduction' }, { name: 'Charge', description: 'Gap closer' }], hotkey3: [{ name: 'Divine Strike', description: 'Holy AoE' }, { name: 'Consecration', description: 'Holy ground zone' }, { name: 'Blessing', description: 'Buff allies' }], hotkey4: { name: 'Judgment', description: 'Massive holy AoE + heal' }, passive: [{ name: 'Holy Dmg', description: '+holy dmg' }, { name: 'Self Heal', description: '+heal on hit' }, { name: 'Resilience', description: '+defense' }] } },
      { id: 'hammer_ember', name: 'Ember Hammer', lore: 'Forged in volcanic fire', stats: { damage: { base: 64, perTier: 16 }, hp: { base: 125, perTier: 31 }, mana: { base: 25, perTier: 12 }, crit: { base: 3, perTier: 0.5 }, block: { base: 6, perTier: 1.5 }, defense: { base: 28, perTier: 8 } }, skills: { hotkey1: { name: 'Flame Smash', description: 'Burn on hit' }, hotkey2: [{ name: 'Ground Slam', description: 'AoE stun' }, { name: 'Shield Wall', description: 'Damage reduction' }, { name: 'Charge', description: 'Gap closer' }], hotkey3: [{ name: 'Lava Slam', description: 'AoE burn' }, { name: 'Molten Shield', description: 'Reflect fire' }, { name: 'Ignite', description: 'Explode burns' }], hotkey4: { name: 'Volcanic Eruption', description: 'Massive fire AoE' }, passive: [{ name: 'Burn Mastery', description: '+burn dmg' }, { name: 'Heavy Hitter', description: '+dmg' }, { name: 'Resilience', description: '+defense' }] } },
      { id: 'hammer_frost', name: 'Frost Hammer', lore: 'Frozen glacial might', stats: { damage: { base: 60, perTier: 15 }, hp: { base: 135, perTier: 34 }, mana: { base: 35, perTier: 18 }, crit: { base: 2, perTier: 0.4 }, block: { base: 8, perTier: 2 }, defense: { base: 34, perTier: 10 } }, skills: { hotkey1: { name: 'Frost Smash', description: 'Slow on hit' }, hotkey2: [{ name: 'Ground Slam', description: 'AoE stun' }, { name: 'Shield Wall', description: 'Damage reduction' }, { name: 'Charge', description: 'Gap closer' }], hotkey3: [{ name: 'Glacial Slam', description: 'AoE freeze' }, { name: 'Ice Armor', description: 'Damage absorb' }, { name: 'Shatter', description: 'Break frozen' }], hotkey4: { name: 'Absolute Zero', description: 'Massive freeze AoE' }, passive: [{ name: 'Slow Mastery', description: '+slow duration' }, { name: 'Freeze Duration', description: '+freeze time' }, { name: 'Resilience', description: '+defense' }] } }
    ]
  },
  // 6 special "weapon" types for spellbook / skill sheet selection
  TOME: { id: 'TOME', name: 'Tome', icon: '📖', category: 'magic', weapons: [ { id: 'tome_arcane', name: 'Arcane Tome', lore: 'Holds forbidden spells', stats: { damage: { base: 30, perTier: 8 }, hp: { base: 40, perTier: 10 }, mana: { base: 120, perTier: 30 }, crit: { base: 4, perTier: 0.6 }, block: { base: 0, perTier: 0 }, defense: { base: 5, perTier: 2 } }, skills: { hotkey1: { name: 'Arcane Missiles', description: 'Multiple magic bolts' }, hotkey2: [], hotkey3: [], hotkey4: { name: 'Meteor', description: 'Call down destruction' }, passive: [] } } ] },
  SHIELD: { id: 'SHIELD', name: 'Shield', icon: '🛡️', category: 'melee', weapons: [ { id: 'shield_kite', name: 'Kite Shield', lore: 'Sturdy defense', stats: { damage: { base: 20, perTier: 5 }, hp: { base: 150, perTier: 35 }, mana: { base: 10, perTier: 5 }, crit: { base: 1, perTier: 0.2 }, block: { base: 25, perTier: 4 }, defense: { base: 40, perTier: 10 } }, skills: { hotkey1: { name: 'Shield Bash', description: 'Stun with shield' }, hotkey2: [], hotkey3: [], hotkey4: { name: 'Fortress', description: 'Full party defense' }, passive: [] } } ] },
  WAND: { id: 'WAND', name: 'Wand', icon: '🪄', category: 'magic', weapons: [ { id: 'wand_basic', name: 'Apprentice Wand', lore: 'Simple focus', stats: { damage: { base: 35, perTier: 9 }, hp: { base: 50, perTier: 12 }, mana: { base: 80, perTier: 25 }, crit: { base: 7, perTier: 1 }, block: { base: 0, perTier: 0 }, defense: { base: 6, perTier: 2 } }, skills: { hotkey1: { name: 'Magic Bolt', description: 'Fast projectile' }, hotkey2: [], hotkey3: [], hotkey4: { name: 'Elemental Surge', description: 'Burst spell' }, passive: [] } } ] },
  GRIMOIRE: { id: 'GRIMOIRE', name: 'Grimoire', icon: '📜', category: 'magic', weapons: [ { id: 'grimoire_dark', name: 'Dark Grimoire', lore: 'Bound demon knowledge', stats: { damage: { base: 45, perTier: 11 }, hp: { base: 60, perTier: 15 }, mana: { base: 140, perTier: 35 }, crit: { base: 5, perTier: 0.8 }, block: { base: 0, perTier: 0 }, defense: { base: 8, perTier: 3 } }, skills: { hotkey1: { name: 'Curse', description: 'Weaken enemy' }, hotkey2: [], hotkey3: [], hotkey4: { name: 'Apocalypse', description: 'Massive ritual' }, passive: [] } } ] },
  NIMBLE_FINGERS: { id: 'NIMBLE_FINGERS', name: 'Nimble Fingers', icon: '🖐️', category: 'melee', weapons: [ { id: 'nimble_rogue', name: 'Rogue Tricks', lore: 'Fast hands', stats: { damage: { base: 40, perTier: 9 }, hp: { base: 70, perTier: 18 }, mana: { base: 20, perTier: 8 }, crit: { base: 9, perTier: 1.4 }, block: { base: 5, perTier: 1 }, defense: { base: 12, perTier: 3 } }, skills: { hotkey1: { name: 'Quick Jab', description: 'Fast multi attack' }, hotkey2: [], hotkey3: [], hotkey4: { name: 'Assassinate', description: 'Lethal strike' }, passive: [] } } ] },
  DUAL_WIELD: { id: 'DUAL_WIELD', name: 'Dual Wield', icon: '⚔️', category: 'melee', weapons: [ { id: 'dual_blades', name: 'Twin Blades', lore: 'Two weapons as one', stats: { damage: { base: 42, perTier: 10 }, hp: { base: 85, perTier: 20 }, mana: { base: 15, perTier: 6 }, crit: { base: 8, perTier: 1.2 }, block: { base: 6, perTier: 1.2 }, defense: { base: 15, perTier: 4 } }, skills: { hotkey1: { name: 'Flurry', description: 'Rapid strikes' }, hotkey2: [], hotkey3: [], hotkey4: { name: 'Whirlwind', description: 'Spin attack' }, passive: [] } } ] }
};

export function calculateWeaponStats(weapon: Weapon, tier: number): {
  damage: number;
  hp: number;
  mana: number;
  crit: number;
  block: number;
  defense: number;
} {
  const t = Math.max(1, Math.min(8, tier)) - 1;
  return {
    damage: Math.round(weapon.stats.damage.base + weapon.stats.damage.perTier * t),
    hp: Math.round(weapon.stats.hp.base + weapon.stats.hp.perTier * t),
    mana: Math.round(weapon.stats.mana.base + weapon.stats.mana.perTier * t),
    crit: parseFloat((weapon.stats.crit.base + weapon.stats.crit.perTier * t).toFixed(1)),
    block: parseFloat((weapon.stats.block.base + weapon.stats.block.perTier * t).toFixed(1)),
    defense: Math.round(weapon.stats.defense.base + weapon.stats.defense.perTier * t),
  };
}

export function getWeaponSkillBonus(skillLevel: number): number {
  return Math.min(10, Math.max(0, skillLevel * 0.1));
}
