/**
 * Direct Railway game-server origin for GRUDOX arcade probes.
 * Vercel-hosted shells proxy /api/*; upstream health is /api/health (not /health).
 *
 * Production **onset pattern** (player journey + sector entries) is also published to:
 *   CDN  catalogs/warlords/onset-pattern.json
 *   D1   production_catalog key=onset-pattern
 * Regenerated by: node scripts/publish-production-world.mjs
 */
import { FLEET_URLS } from "./manifest";
import {
  THREE_HOME_ISLAND_PATH,
  THREE_OPEN_WORLD_PATH,
  THREE_WORLD_MAP_PATH,
  threeOpenWorldUrl,
} from "./gameDeployments";

export const LIVE_GAME_SERVER_ORIGIN = FLEET_URLS.gameData;
export const LIVE_GAME_SERVER_HEALTH = `${LIVE_GAME_SERVER_ORIGIN}/api/health` as const;

/** Canonical production onset — starter Haven → world map → Fabled core optional. */
export const PRODUCTION_ONSET_PATTERN = {
  version: "2.0.0",
  worldSeedDefault: "grudge-world-1",
  steps: [
    { id: "intro", path: "/intro" },
    { id: "create", path: "/create-character" },
    { id: "tutorial", path: "/tutorial" },
    { id: "open_world", path: THREE_OPEN_WORLD_PATH },
    { id: "world_map", path: THREE_WORLD_MAP_PATH },
    {
      id: "fabled_core",
      path: threeOpenWorldUrl({
        sector: "frostbite_expanse",
        city: "runeforge_hold",
      }),
    },
    { id: "home_island", path: THREE_HOME_ISLAND_PATH },
  ],
  sources: {
    assetsCdn: FLEET_URLS.assets,
    objectStore: FLEET_URLS.objectStore,
    accounts: FLEET_URLS.auth,
    characters: FLEET_URLS.charactersHub,
  },
} as const;