/**
 * Toon Soldiers (chicken_gun) — fleet SSOT for Hero RTS / shooters / editors.
 * Generated by grudge-arena/scripts/process-toon-soldiers-chicken-gun.mjs
 * Do not hand-edit character mesh keys — re-run the process script.
 */

import { FLEET_URLS } from "./manifest";

export const TOON_SOLDIERS_CDN = `${FLEET_URLS.assets}/models/toon-soldiers` as const;
export const TOON_SOLDIERS_CATALOG_URL =
  "https://objectstore.grudge-studio.com/api/v1/toon-soldiers-catalog.json" as const;

export type ToonSoldierClass =
  | "scout"
  | "engineer"
  | "gunner"
  | "infantry"
  | "medic"
  | "sniper";

export type ToonAnimPack = "rifle" | "pistol";

export interface ToonSoldierDef {
  id: string;
  classId: ToonSoldierClass;
  variant: string;
  label: string;
  role: string;
  weapon: string;
  animPack: ToonAnimPack;
  unitTypes: string[];
  stats: { hp: number; speed: number; damage: number; range: number };
  meshUrl: string;
  localPath: string;
  r2Key: string;
  nativeClips: string[];
  controllerStates: {
    idle: string | null;
    walk: string | null;
    run: string | null;
    attack: string | null;
  };
}

const RAW = [
  {
    "id": "toon:scout",
    "classId": "scout",
    "variant": "a",
    "label": "Scout A",
    "role": "skirmisher",
    "weapon": "pistol",
    "animPack": "pistol",
    "unitTypes": [
      "hero",
      "infantry"
    ],
    "stats": {
      "hp": 90,
      "speed": 1.15,
      "damage": 18,
      "range": 12
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/scout/scout-a.glb",
    "localPath": "/models/toon-soldiers/scout/scout-a.glb",
    "r2Key": "models/toon-soldiers/scout/scout-a.glb",
    "nativeClips": [
      "TS_Body_03_scoutAction",
      "TS_Head_02_ScoutAction"
    ],
    "controllerStates": {
      "idle": "TS_Body_03_scoutAction",
      "walk": null,
      "run": null,
      "attack": "TS_Body_03_scoutAction"
    }
  },
  {
    "id": "toon:scout:b",
    "classId": "scout",
    "variant": "b",
    "label": "Scout B",
    "role": "skirmisher",
    "weapon": "pistol",
    "animPack": "pistol",
    "unitTypes": [
      "hero",
      "infantry"
    ],
    "stats": {
      "hp": 90,
      "speed": 1.15,
      "damage": 18,
      "range": 12
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/scout/scout-b.glb",
    "localPath": "/models/toon-soldiers/scout/scout-b.glb",
    "r2Key": "models/toon-soldiers/scout/scout-b.glb",
    "nativeClips": [
      "TS_Body_03_scoutAction.001",
      "TS_Head_02_ScoutAction.002"
    ],
    "controllerStates": {
      "idle": "TS_Body_03_scoutAction.001",
      "walk": null,
      "run": null,
      "attack": "TS_Body_03_scoutAction.001"
    }
  },
  {
    "id": "toon:engineer",
    "classId": "engineer",
    "variant": "a",
    "label": "Engineer A",
    "role": "support",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "worker",
      "hero"
    ],
    "stats": {
      "hp": 100,
      "speed": 1,
      "damage": 14,
      "range": 10
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/engineer/engineer-a.glb",
    "localPath": "/models/toon-soldiers/engineer/engineer-a.glb",
    "r2Key": "models/toon-soldiers/engineer/engineer-a.glb",
    "nativeClips": [
      "TS_Body_05_engineerAction",
      "TS_Head_05_engineerAction"
    ],
    "controllerStates": {
      "idle": "TS_Body_05_engineerAction",
      "walk": null,
      "run": null,
      "attack": "TS_Body_05_engineerAction"
    }
  },
  {
    "id": "toon:engineer:b",
    "classId": "engineer",
    "variant": "b",
    "label": "Engineer B",
    "role": "support",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "worker",
      "hero"
    ],
    "stats": {
      "hp": 100,
      "speed": 1,
      "damage": 14,
      "range": 10
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/engineer/engineer-b.glb",
    "localPath": "/models/toon-soldiers/engineer/engineer-b.glb",
    "r2Key": "models/toon-soldiers/engineer/engineer-b.glb",
    "nativeClips": [
      "Armature.002Action.002",
      "TS_Body_05_engineerAction.001",
      "TS_Head_05_engineerAction.001"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.002",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.002"
    }
  },
  {
    "id": "toon:gunner",
    "classId": "gunner",
    "variant": "a",
    "label": "Gunner A",
    "role": "heavy",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "infantry",
      "hero"
    ],
    "stats": {
      "hp": 120,
      "speed": 0.9,
      "damage": 28,
      "range": 16
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/gunner/gunner-a.glb",
    "localPath": "/models/toon-soldiers/gunner/gunner-a.glb",
    "r2Key": "models/toon-soldiers/gunner/gunner-a.glb",
    "nativeClips": [
      "Armature.001Action.005",
      "Armature.002Action.003",
      "TS_Body_02_gunnerAction",
      "TS_Head_15_gunner_onlyAction.002"
    ],
    "controllerStates": {
      "idle": "Armature.001Action.005",
      "walk": null,
      "run": null,
      "attack": "TS_Body_02_gunnerAction"
    }
  },
  {
    "id": "toon:gunner:b",
    "classId": "gunner",
    "variant": "b",
    "label": "Gunner B",
    "role": "heavy",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "infantry",
      "hero"
    ],
    "stats": {
      "hp": 120,
      "speed": 0.9,
      "damage": 28,
      "range": 16
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/gunner/gunner-b.glb",
    "localPath": "/models/toon-soldiers/gunner/gunner-b.glb",
    "r2Key": "models/toon-soldiers/gunner/gunner-b.glb",
    "nativeClips": [
      "Armature.001Action.006",
      "Armature.002Action.004",
      "TS_Body_02_gunnerAction.001",
      "TS_Head_15_gunner_only.001Action"
    ],
    "controllerStates": {
      "idle": "Armature.001Action.006",
      "walk": null,
      "run": null,
      "attack": "TS_Head_15_gunner_only.001Action"
    }
  },
  {
    "id": "toon:infantry",
    "classId": "infantry",
    "variant": "a",
    "label": "Infantry A",
    "role": "line",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "infantry"
    ],
    "stats": {
      "hp": 110,
      "speed": 1,
      "damage": 22,
      "range": 14
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/infantry/infantry-a.glb",
    "localPath": "/models/toon-soldiers/infantry/infantry-a.glb",
    "r2Key": "models/toon-soldiers/infantry/infantry-a.glb",
    "nativeClips": [
      "Armature.002Action.005",
      "TS_Body_01_infantryAction"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.005",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.005"
    }
  },
  {
    "id": "toon:infantry:b",
    "classId": "infantry",
    "variant": "b",
    "label": "Infantry B",
    "role": "line",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "infantry"
    ],
    "stats": {
      "hp": 110,
      "speed": 1,
      "damage": 22,
      "range": 14
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/infantry/infantry-b.glb",
    "localPath": "/models/toon-soldiers/infantry/infantry-b.glb",
    "r2Key": "models/toon-soldiers/infantry/infantry-b.glb",
    "nativeClips": [
      "Armature.002Action.006"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.006",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.006"
    }
  },
  {
    "id": "toon:medic",
    "classId": "medic",
    "variant": "a",
    "label": "Medic A",
    "role": "healer",
    "weapon": "pistol",
    "animPack": "pistol",
    "unitTypes": [
      "support",
      "hero"
    ],
    "stats": {
      "hp": 95,
      "speed": 1.05,
      "damage": 12,
      "range": 10
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/medic/medic-a.glb",
    "localPath": "/models/toon-soldiers/medic/medic-a.glb",
    "r2Key": "models/toon-soldiers/medic/medic-a.glb",
    "nativeClips": [
      "Armature.002Action.007",
      "TS_Body_06_medicAction"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.007",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.007"
    }
  },
  {
    "id": "toon:medic:b",
    "classId": "medic",
    "variant": "b",
    "label": "Medic B",
    "role": "healer",
    "weapon": "pistol",
    "animPack": "pistol",
    "unitTypes": [
      "support",
      "hero"
    ],
    "stats": {
      "hp": 95,
      "speed": 1.05,
      "damage": 12,
      "range": 10
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/medic/medic-b.glb",
    "localPath": "/models/toon-soldiers/medic/medic-b.glb",
    "r2Key": "models/toon-soldiers/medic/medic-b.glb",
    "nativeClips": [
      "Armature.002Action.008",
      "TS_Body_06_medicAction.001"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.008",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.008"
    }
  },
  {
    "id": "toon:sniper",
    "classId": "sniper",
    "variant": "a",
    "label": "Sniper A",
    "role": "marksman",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "infantry",
      "hero"
    ],
    "stats": {
      "hp": 85,
      "speed": 0.95,
      "damage": 40,
      "range": 28
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/sniper/sniper-a.glb",
    "localPath": "/models/toon-soldiers/sniper/sniper-a.glb",
    "r2Key": "models/toon-soldiers/sniper/sniper-a.glb",
    "nativeClips": [
      "Armature.002Action.009",
      "TS_Body_04_sniperAction",
      "TS_Head_04_sniperAction"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.009",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.009"
    }
  },
  {
    "id": "toon:sniper:b",
    "classId": "sniper",
    "variant": "b",
    "label": "Sniper B",
    "role": "marksman",
    "weapon": "rifle",
    "animPack": "rifle",
    "unitTypes": [
      "infantry",
      "hero"
    ],
    "stats": {
      "hp": 85,
      "speed": 0.95,
      "damage": 40,
      "range": 28
    },
    "meshUrl": "https://assets.grudge-studio.com/models/toon-soldiers/sniper/sniper-b.glb",
    "localPath": "/models/toon-soldiers/sniper/sniper-b.glb",
    "r2Key": "models/toon-soldiers/sniper/sniper-b.glb",
    "nativeClips": [
      "Armature.002Action.010",
      "TS_Body_04_sniperAction.001",
      "TS_Head_04_sniperAction.001"
    ],
    "controllerStates": {
      "idle": "Armature.002Action.010",
      "walk": null,
      "run": null,
      "attack": "Armature.002Action.010"
    }
  }
] as const;

export const TOON_SOLDIERS: ToonSoldierDef[] = RAW as unknown as ToonSoldierDef[];

export const TOON_SOLDIER_BY_ID: Record<string, ToonSoldierDef> = Object.fromEntries(
  TOON_SOLDIERS.map((t) => [t.id, t]),
);

export const TOON_CLASS_DEFAULT: Record<ToonSoldierClass, ToonSoldierDef> = {
  scout: TOON_SOLDIER_BY_ID["toon:scout"],
  engineer: TOON_SOLDIER_BY_ID["toon:engineer"],
  gunner: TOON_SOLDIER_BY_ID["toon:gunner"],
  infantry: TOON_SOLDIER_BY_ID["toon:infantry"],
  medic: TOON_SOLDIER_BY_ID["toon:medic"],
  sniper: TOON_SOLDIER_BY_ID["toon:sniper"],
};

/** Faction → default toon hero (Hero Commander RTS). */
export const FACTION_TOON_HERO: Record<string, string> = {
  OrangeStar: "toon:scout",
  BlueMoon: "toon:sniper",
  GreenEarth: "toon:medic",
  YellowComet: "toon:gunner",
  BlackHole: "toon:engineer",
};

export function resolveToonMesh(assetId: string): string {
  const def = TOON_SOLDIER_BY_ID[assetId] ?? TOON_CLASS_DEFAULT[assetId as ToonSoldierClass];
  return def?.meshUrl ?? `${TOON_SOLDIERS_CDN}/scout/scout-a.glb`;
}

export const TOON_GUNPLAY_PACKS = {
  "rifle": {
    "idle": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/rifle/idle.json",
    "walk": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/rifle/walk forward.json",
    "run": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/rifle/run forward.json",
    "attack": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/rifle/firing.json",
    "walkBack": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/rifle/walk backward.json",
    "runBack": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/rifle/run backward.json"
  },
  "pistol": {
    "idle": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/pistol idle.json",
    "walk": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/pistol walk.json",
    "run": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/pistol run.json",
    "attack": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/gunplay.json",
    "walkBack": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/pistol walk backward.json",
    "runBack": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/pistol run backward.json",
    "strafe": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/pistol/pistol strafe.json"
  },
  "locomotion": {
    "walk": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/locomotion/walking.json",
    "run": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/locomotion/running.json",
    "sprint": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/uploads_2026_06/locomotion/running.json",
    "dodge": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/locomotion/dodging.json",
    "leftStrafe": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/locomotion/left strafe walking.json",
    "rightStrafe": "https://grudge-arena.grudge-studio.com/api/assets/anims/baked/locomotion/right strafe walking.json"
  }
} as const;
